### ISSUE TITLE
PASCAL highlighting

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#100]
Hi, How to set two color for pascal keyword
for example i want to colored (string integer char array) in red
and the other in blue
i used this code 
Scintilla1.SetKeywords(0, "absolute abstract and ... " )
 Scintilla1.Styles(Style.Pascal.Word).ForeColor = Color.blue

**Comment by jacobslusser** [comment]
The wiki contains guides for setting up sytax highlighting in [C#](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting) and [Python](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes). Follow the guides but instead of using C# and Python style constants, enum values, and keywords, use the `Style.Pascal` constants, `Lexer.Pascal`, and Pascal keywords.

There have also been some previous [discussions](https://github.com/jacobslusser/ScintillaNET/issues?utf8=%E2%9C%93&q=pascal) about setting up Pascal syntax highlighting that you might find helpful.

**Comment by METOUIA7** [comment]
the lexer work good but i want to set more then one color for the keywords
it's possible to set two colors for the keywords

**Comment by jacobslusser** [comment]
> it's possible to set two colors for the keywords

It depends on the lexer. Some lexers allow you to specify more than one keyword list which allows you to use more than one style, however, I don't believe the Pascal lexer supports that.

**Comment by METOUIA7** [comment]
thanks for help
