### ISSUE TITLE
Sql Lexer Style

### ISSUE THREAD

**Issue by tomszgh** [jacobslusser/ScintillaNET#104]
I'm trying to use automatic highlighting in SQL. After the following code, I would expect the word "CREATE" to be blue, but it is not:

scintilla.Lexer = ScintillaNET.Lexer.Sql;
scintilla.Styles[Style.Sql.Word].ForeColor = Color.Blue;
scintilla.SetKeywords(0, "CREATE");

What am I doing wrong?

**Comment by jacobslusser** [comment]
**TL;DR**
Try:

```cs
scintilla.SetKeywords(0, "create");
```

**Explanation:**
Generally speaking, Scintilla looks for matching keywords by doing a *case-sensitive* comparison. For languages like SQL with *case-insensitive* keywords, it works around that default behavior by converting all words found by the lexer to lowercase before matching them to the keyword lists. Thus SQL keywords should be specified in lowercase so that when the document finds `"CREATE"` or `"CrEaTe"`, they will all be converted to `"create"` before attempting to match them against the keyword list.

**Comment by tomszgh** [comment]
Thank you, that worked.
