### ISSUE TITLE
Assembly generation failed -- Referenced assembly 'ScinetillNet' does not have a strong name

### ISSUE THREAD

**Issue by tttmack** [jacobslusser/ScintillaNET#11]
Hello, I'm not sure if this is an issue or not, but with both the 3.2RC and 3.3 versions, I get "Assembly generation failed -- Referenced assembly 'ScintillaNet' does not have a strong name" when building.

I managed to get rid of the error using the steps here: http://www.codeproject.com/Tips/341645/Referenced-assembly-does-not-have-a-strong-name

Is there a way to get the release to have a strong name by default or am I missing a step in my setup? I installed via Nuget.

Thanks for your help!

**Comment by jacobslusser** [comment]
I haven't added a strong-name to ScintillaNET because I've always found them to be a major headache. Your problem is a prime example of that. ;)

I would guess you are using a strong-name for your main project (more specifically, the project that is referencing ScintillaNET). A strong-named project (you) can only reference other strong-named projects (ScintillaNET).

So I guess the question is whether I should add a strong-name to ScintillaNET? Like I said, I'm inclined not to, but I'll throw it out there for the group and see what our audience thinks. While that's being debated I might suggest you fork the ScintillaNET repo and add your strong-name support for anyone who wants it. When/if we decide to add the support I'll merge it in.

P.S. Just curious, what are your reasons for using strong-names?

**Comment by tttmack** [comment]
I'm using it in an Excel Addin, which uses COM Interop, and seems to need to have a strong name.

**Comment by tttmack** [comment]
Hello, any update whether you will be adding a strong name to ScintillaNET?

**Comment by jacobslusser** [comment]
I certainly don't want to alienate and of our users, but I've been researching the implications of signing the assembly with a strong name and I think it's a bad idea. Like I said, I've had bad personal experiences, and the research I've done over the last couple days has only served to remind me of that.

I know this choice will be unpopular for some developers who want signed assemblies, but I'm of the opinion that the majority do not want it signed and doing so will pose problems for them.

I think the best way to handle your situation is to build the source yourself and sign it. As I also said before if you think there is value in doing so I would suggest forking the repo and maintained a "signed version". That is the beauty of hosting ScintillaNET at GitHub.

If that's too much work for you, you might look into a tool that can sign an existing assembly such as [StrongNameSigner](https://github.com/brutaldev/StrongNameSigner). I have no personal experience with this tool, but I know it and others like it can make doing this very easy.

**Comment by BrisingrAerowing** [comment]
Some projects I have seen provide both signed and unsigned assemblies, using conditional compilation and the [AssemblyKeyFileAttribute](https://msdn.microsoft.com/en-us/library/system.reflection.assemblykeyfileattribute(v=vs.110).aspx) with configurations like Release (which is unsigned) and ReleaseSigned (which is signed). Debug is usually always unsigned (from what I have seen).

I know Mono uses the attribute in their class library, but they don't use the conditional compilation.

**Comment by jacobslusser** [comment]
Support for building a signed version of ScintillaNET has been added and can be done by selecting "ReleaseSigned" from the build configuration.

Thanks go to @BrisingrAerowing.

**Comment by BrisingrAerowing** [comment]
@jacobslusser Glad to help. I agree that Strong Naming can and does cause many issues, but there are a number of places where it is required (like COM interop, as mentioned in the original report).
