### ISSUE TITLE
The simplest way to activate a highlight syntax

### ISSUE THREAD

**Issue by assismauro** [jacobslusser/ScintillaNET#14]
Hi,

In older versions, it was necessary only to set:

scintilla.ConfigurationManager.Language = "python";

to have a nice python editor up and running.

As I moved to 3.3 version, initially I tryied to do:

scintilla.Lexer = Lexer.Python;

But anything happened, that is, the editor didn´t show syntax highlighting.

Checking README.md file, I saw an example showing how to configure a C# editor defining all features corresponding to Visual Studio-style editor.

It´s necessary to do those definitions for all languages? That is, there´s no way to define Scintilla as a Python, R or MSSQL only defining a property.

If so, could you find examples for those other languages?

Tks in advance,

Mauro Assis

**Comment by jacobslusser** [comment]
This question has been asked a couple times.

- Issue #5 - Outlining how you plan on handling highlighting going forward?
- Issue #7 - Questions

Configuring the Python, R, or SQL lexer is no more difficult than the C# lexer. Yes, it requires a little extra code on your part, but it is much easier for developers to customize than the undocumented XML configuration system used in past versions of ScintillaNET.

Is the README.md documentation unclear or difficult to follow? My assumption is that it should be easy for developers to translate those concepts to other lexer and styles, but if that's not the case I'm interested in your feedback.

**Comment by assismauro** [comment]
Jacob,

It´s clear for me that to move away from undocumented dll was a great thing. However, I never dig into this file in the past.

On the other hand, if I´m not interested in go deep in details about a langage itself and I´m interested in provide Scintilla in my app (or upgrade from an older version) without effort, it wold be easy to have some way to do that only indicanting the language even in runtime, as I´m doing in my application that supports R, Python & SQL.

Now I´ll have to write code to define things like reserved words etc for those three languages.

I think if you provide examples with those common languages up and running and suggests a nice way to switch ammong them in run-time would help not only me, but other "lazy guys that uses the ond way scintilla.

Tks,

Mauro Assis

**Comment by glopesdev** [comment]
Hi all,

I've just discovered ScintillaNET and I just find it amazing, great work!
However, I have to echo the difficulties outlined in this question in how to set it up and running.

I don't mind having to specify style colors and properties programmatically, but what I'm finding is that the style definitions don't match what I would expect from the Lexer.

For example:
scintilla.Styles[Style.Python.Word].ForeColor = ColorTranslator.FromHtml("#0000ff");
scintilla.Styles[Style.Python.Word2].ForeColor = ColorTranslator.FromHtml("0000ff");

should presumably set Python keywords to blue. However, for some reason these keywords are not in the lexer (e.g. def, import, class, etc, are all missing!). This is annoying because then it becomes necessary to add the keywords by hand.

While it is definitely possible to work around this, I would expect the Lexer to already provide this information...

Anyway, yes, complete examples for a couple of major languages would be nice. Also line numbers don't seem to show up and the horizontal bar is always there regardless of line width. I don't know if these are known issues or if I should start logging this into the bug tracker.

**Comment by assismauro** [comment]
Well, it seems to me that I´m not alone in my concerns about the new ScintillaNet approach...

glopesdev, in fact the old versions of ScintillaNet used to be easier to config. It was necessary only to set de desired language:

scintilla.ConfigurationManager.Language = "python";

and everything goes like a charm.

So, despite in the old version we had to deal with external dlls, I moved back to the old version as did a friend that is a user of ScintillaNet as well.

**Comment by jacobslusser** [comment]
@assismauro Your concern is important to me. I'm not brushing it off. I believe I had asked you for suggestions on how to make the instructions clearer so that you and other developers can benefit from it. To simply say that it doesn't do what you want doesn't help anybody. You asked for an example on setting up additional languages such as R, SQL, etc... Should I stop spending my personal time on that now that you don't want to use ScintillaNET v3?

@glopesdev Some of the questions you have about line numbers and the horizontal scrollbar have been answered in the Wiki and/or Issues tracker. Some of the other concerns you have about setting up keywords are an artifact of the way the native Scintilla component works. My philosophy is that developers who understand how the native component works will be better equipped to customize it for their own needs or troubleshoot problems when things don't work. Obviously some people disagree with me on that philosophy. 

It comes down to this... do you want flexibility or do you want ease?

**Comment by assismauro** [comment]
Starting from the end: I want both. How about you?

@jacobslusser, I moved back to the old version because I prefer the old approach, while you can´t provide the examples I suggest you. I´m not asking you to implement it in a hurry, but in the other hand  in the project I´m using ScintillaNet I´ve a schedule to fulfill. In my opinion, as I learned how to deal with the DLLs, it´s better to move back to the old version.  

Many thanks for release ScintillaNet to us, it´s amazing.

**Comment by glopesdev** [comment]
@jacobslusser Thank you for the quick response. To clarify, even though I'm a new user to ScintillaNET, I really like the way the library is organized and I also much enjoy the provided flexibility, I think it should continue exactly as it is! Now that I understand it, I wouldn't change a single thing about the architecture, it's great!

However, my perspective as someone completely new facing the API it was a bit surprising to see nothing highlighted when I selected the Lexer from the windows forms editor. I guess we tend to be a bit lazy when we have the nice windows forms editor where you can just pop a new control and quickly try it out.

I think it would be nice to have some default styles for each lexer, however, what I really think is the important bit is the keywords... somehow I feel the keyword set should be part of the lexer... or at least there should be some default string constants for each of the built-in languages. Is there a reason why one of these solutions doesn't make sense? Maybe I'm missing something...

Also, I did check the README.MD, but somehow some of these things (like line numbers and other things) were not immediately clear, but it may be my problem.

Anyway, all in all I think it's a great library! It's really a tricky but very recurrent problem and it's absolutely amazing to just finally have a clean solution to deal with it. Thank you so much! These suggestions are merely an attempt to try and improve what's already a great and useful library.

**Comment by jacobslusser** [comment]
Thank you @assismauro  and @glopesdev  for your compliments. Here's what I plan to do: because I'm still not convinced that baking keywords and lexer styles into the core ScintillaNET component is the way to go I will stick with my plan to provide better examples. I will create a new page in the [Wiki](https://github.com/jacobslusser/ScintillaNET/wiki) that will host user contributed recipes for common tasks like language setups. I'll get it started with a Python snippet sometime later today.

**Comment by glopesdev** [comment]
Great, that already sounds like a great compromise! Thanks for your help.

**Comment by assismauro** [comment]
It will be great to have that, thank you very much.

**Comment by robmburke** [comment]
I think there just needs to be good premade examples that can be copy/pasted into a users code.  If the wiki contains consistent examples, and that ends up being the go-to place to get them, then I think that is the best place to put it.  It isn't fair that jacob should have to keep track of all of the languages for us, especially when most of them wouldn't even be used.  If he got some of the common languages going on the wiki as examples and then allowed users to add their custom setup that follow his templates, that would be awesome.

**Comment by jacobslusser** [comment]
Alright. I created a new page in the Wiki for [User Submitted Recipes](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes) and got the ball rolling with a Python recipe that should easy to copy-and-paste. I welcome any more user submissions for language configurations or any ScintillaNET technique in general.

This feels right to me. I persisted in pushing back on this issue because I wanted to the address the need in the correct way and I think this is it. Thanks everyone for your feedback.
