### ISSUE TITLE
Determine Indicator group

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#146]
Is there a quick way during DwellStart to determine which Indicator group(s) are being used by the current text?

**Comment by jacobslusser** [comment]
I have some unfinished documentation on indicators tucked away here [https://github.com/jacobslusser/ScintillaNET/blob/master/docs/sections/indicators.md](https://github.com/jacobslusser/ScintillaNET/blob/master/docs/sections/indicators.md). Under the section *Navigating Indicators* you should find a description of techniques you can use to determine what indicators are present for a given document position, which used with the `DwellStart` event, should get you what you're looking for.

**Comment by robmburke** [comment]
Maybe I'm totally confused since I've never used uint/bitmap stuff before or maybe I'm explaining myself wrong.

I have implemented something similar to your example.  However, I use two different indicators.  As far as my current knowledge goes, I can hard-code Indicators with an index: `scintilla.Indicators[0]`, which is what your example shows.

What I need to be able to do is know which indexes belong to my current selection so that I can call different tooltips based on that.  Now, I understand the bitmap gives you this information. However, I don't understand how to figure out which indexes are actually being used because the number returned by IndicicatorsAllOnFor returns a number I don't understand how to interpret.

Using your example above, I could test for each one, but that is a lot of code.  Also, if there ever happened to be a combination of two indicators in one range, how do I actually know which ones are being used and which ones to show tooltips for, especially if there are two indicator indexes and I want the message for one to take precedent over the other.

**Comment by jacobslusser** [comment]
Bitmasks can be confusing if you're not used to them. What the `Scintilla.IndicatorAllOnFor` method returns is a 32-bit value where each bit indicates which indicators are used for that position. For example:

```
0b00000000000000000000000000000000 // No indicators
0b00000000000000000000000000000001 // Indicator 0 is 'on'
0b00000000000000000000000000000010 // Indicator 1 is 'on'
0b00000000000000000000000000000101 // Indicators 0 and 2 are 'on'
0b00000000000000000000000000001101 // Indicators 0, 2, and 3 are 'on'
// etc...
```

Each bit corresponds to an indicator index. There are 32 possible bits in a `[u]int` and 32 possible indicator indexes, thus, every indicator state for a single position can be represented in this very compact form.

*NOTE: When represented in binary form as I've done above, this becomes easy to see; but if you were to view the value returned from `IndicatorAllOnFor` in the Visual Studio debugger it would likely look like a seemingly random number. That is because, by default, Visual Studio will show numbers in base10 (decimal), or base16 (hexadecimal)... not base2 (binary) as I've done above.*

To determine if one of these is set you only need to see if there is a `1` at the bit representing the indicator index you're interested in. A helper method to do that would look something like this:

```cs
private bool IndicatorOnFor(int indicator, int pos)
{
    var bitmap = scintilla.IndicatorAllOnFor(pos);
    var flag = (1 << indicator);
    return ((bitmap & flag) == flag);
}
```

To determine if indicator `2` is being used at position `330`, you could call it like this:

```cs
var indicator2IsOn = IndicatorOnFor(2, 330);
```

Using an index of `2`, `(1 << indicator)` is a convenient way to generate a mask (`flag`) value of: `0b00000000000000000000000000000100`. It does this by starting with a value of `1` and shifting it two places to the left, i.e. `0b00000000000000000000000000000001` becomes `0b00000000000000000000000000000100`.

When using the AND operator (`&`), the `bitmap` and `flag` values will be compared and only bits that are 'on' for both (i.e. in `bitmap` **AND** in `flag`) will be in the resulting value:

```
// If 'bitmap' has a bit set in position 2
  0b00000000000100000100000010000110 // 'bitmap'
& 0b00000000000000000000000000000100 // 'flag'
-----------------------------------------------------------------------
= 0b00000000000000000000000000000100 // equals 'flag'
```

```
// If 'bitmap' does NOT have a bit set in position 2
  0b00000000000100000100000010000010 // 'bitmap'
& 0b00000000000000000000000000000100 // 'flag'
-----------------------------------------------------------------------
= 0b00000000000000000000000000000000 // does NOT equal 'flag'
```

Thus `((bitmap & flag) == flag)` tells you whether the bitmap has the flag, and in turn, whether your indicator is on for the given position.

As for which tooltip to show if you have multiple indicators set for a given position, that's up to you. You'll likely want to decide which messages is the most important for your user to see and then come up with some kind of application-specific priority.
