### ISSUE TITLE
[Highlighting] Performance problem with accentuated characters.

### ISSUE THREAD

**Issue by VisitorQ** [jacobslusser/ScintillaNET#157]
Hello,
I tried to highlight some specific patterns in a text and I found out that accentuated characters show very poor performance compared to the same non accentuated characters.
I did not expect this erratic behaviour, so it took me some hours to figure out the cause of the problem while working on a french text.

I built a simple demo (WPF application). I wrote a routine to highlight the words surrounded by ** in a sentence and I compared the time to style (in red) the following strings :

1 - "aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua.";
2 - "âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà.";

Here is the result (the times to style are in ms and recorded in the "StyleNeeded" method) :
![styling benchmark](https://cloud.githubusercontent.com/assets/15521119/11674599/bb16c99e-9e22-11e5-916e-58d8c11c7e3c.png)

The result for the string 2 (the one with accentuated characters) is on the right (above picture).

The method below generates the text to be loaded into the editor (scintilla.Text = BuildText()) in the "Window_Loaded" method :

private string BuildText() {
	StringBuilder sb = new StringBuilder();
	string textLine = "aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua aeiouyc **AEIOUY** aeiouy **AEIOUY** eeua.";
	//textLine = "âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà âêîôûŷç **ÂÊÎÔÛŶ** äëïöüÿ **ÄËÏÖÜŸ** éèùà.";

	for (int i = 0; i < 100; i++) {
		sb.Append(textLine);
		sb.Append(Environment.NewLine);
	}

	return sb.ToString();
}

The routine to style the text, "TextStyle" (see below), is called in the "scintilla_StyleNeeded" method :

private void TextStyle(int startPos, int endPos) {
	char currentChar;
	char nextChar;
	int rangeToStyle;

	startPos = scintilla.Lines[scintilla.LineFromPosition(startPos)].Position;

	while (startPos < endPos) {
		rangeToStyle = 0;
		currentChar = (char)scintilla.GetCharAt(startPos);
		nextChar = (char)scintilla.GetCharAt(startPos + 1);

		if (currentChar == '*' && currentChar == nextChar) {
			startPos += 2;
			rangeToStyle = 2;
			do {
				rangeToStyle++;

				currentChar = (char)scintilla.GetCharAt(startPos + rangeToStyle - 2);
				nextChar = (char)scintilla.GetCharAt(startPos + rangeToStyle - 1);
			} while (currentChar != '*' || nextChar == '*');

			scintilla.StartStyling(startPos - 2);
			scintilla.SetStyling(rangeToStyle + 1, StyleStar);
			startPos += rangeToStyle - 2;

			continue;
		}

		startPos++;
	}
}

Is there a property to change in order to get the accentuated characters to be correctly handled ?

In advance, thank you for any help on this issue.

**Comment by jacobslusser** [comment]
I think what you're noticing is more the nature of UTF-8 than anything else. UTF-8 (which Scintilla uses internally to support Unicode) represents Unicode characters with a variable number of bytes. So one character could occupy one byte, or two, or three, or more... depending on the Unicode character. That means for Scintilla to get the character at position N, it has to scan the bytes, counting characters (some of which are one, two, three, etc... bytes long), until it reaches N characters.

ASCII on the other hand always uses one byte for one character. So to get the character at position N you can simply count N bytes.

Within ScintillaNET there are optimizations that will determine whether a line of text is comprised strictly of one-byte wide characters, or whether some of the characters in the line require 2+ bytes. When possible, lines that contain only one-byte wide characters will be able to use the "one byte equals one character" logic, but in your sample text that optimization can't be used.

So chances are your test is not real world and that you're not going to have any actual issues, but it is indeed possible that enough Unicode characters can hinder performance.

That being said, I think you could optimize the code you have to improve performance. For example,  the `GetCharAt` method must perform that byte/character scanning that I just described on every call. If you were to profile your method, I'm certain that would be where most/all of your time is being spent. For that reason, I often write my styling code so that it gets an entire line of text at a time, rather than one character at a time.

**Comment by VisitorQ** [comment]
I've tried to scan the text's characters like this :

	currentChar = scintilla.Text[startPos];
	nextChar = scintilla.Text[startPos + 1];

and I've obtained the same result as with GetCharAt. Therefore, it seems to me that, in general, scanning non-ASCII characters in a text gives poor result for the reasons you put forward. Is that correct ?
Anyway, following your advice, I've rewritten the "TextStyle" method:

private void TextStyle(int startPos, int endPos) {
	string currentLineText;
	int currentLineToStyle = scintilla.LineFromPosition(startPos);
	int lastLineToStyle = scintilla.LineFromPosition(endPos);
	int startTagIndex = 0;
	int endTagIndex = 0;

	while (currentLineToStyle <= lastLineToStyle) {
		currentLineText = scintilla.Lines[currentLineToStyle].Text;
		startTagIndex = currentLineText.IndexOf("**", 0);
		startPos = scintilla.Lines[currentLineToStyle].Position;

		while (startTagIndex > -1) {
			endTagIndex = currentLineText.IndexOf("**", startTagIndex + 2);

			scintilla.StartStyling(startPos + startTagIndex);
			scintilla.SetStyling(endTagIndex - startTagIndex + 2, StyleStar);
			startTagIndex = currentLineText.IndexOf("**", endTagIndex + 2);
		}

		currentLineToStyle++;
	}
}

And here are the new metrics  (the times to style are in ms and recorded in the "StyleNeeded" method) :
![styling benchmark](https://cloud.githubusercontent.com/assets/15521119/11686536/863f5b14-9e81-11e5-880c-f28a8024af5d.png)

It is day and night! Thank you.

One more question. As you can see in the picture above, at startup, the "StyleNeeded" method is called twice and the second time to style not only the visible part of the text (the one visible in the editor's viewport) but all the text. Based on your article "Custom Syntax Highlighting", I thought the "StyleNeeded" event should have been triggered only once and to style only the text visible in the editor's viewport. I wonder if the "Window_Loaded" method is the right place to assign the scintilla.Text property ?

Best regard.

**Comment by jacobslusser** [comment]
The `StyleNeeded` event is raised by the native Scintilla core and not by ScintillaNET so I couldn't say why it might be raised more than would seem needed. I would guess, however, that it will probably want to do a first time run through the entire document to get the potential documents bounds such as height and width, which are dependant on styling, and then only do incremental calls to `StyleNeeded` after that.
