### ISSUE TITLE
Put a line in middle

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#162]
Hi,

How do I put a specific line into view in the middle on screen?

Regards,

**Comment by Aghlara** [comment]
What I mean is I want to move/scroll the yellow line to the middle of screen:
![image](https://cloud.githubusercontent.com/assets/5187409/11761112/5e2969d2-a109-11e5-8d53-3f9613383c64.png)

**Comment by theryan722** [comment]
I haven't tested it, as it's just an idea but I'm imagining that if you get the line number, then get the position of a line that is half of the visible line count down the page, and use the ScrollCaret to go to that line, you could do it. You could even then reset the caret's position to the line you wanted afterwards.

**Comment by Aghlara** [comment]
I use `Lines[lineNumber].EnsureVisible();` to make sure the line is always visible. But that puts it to the last line of the view.
How do I know how many lines can be displayed in my view?

**Comment by Aghlara** [comment]
I can see `FirstVisibleLine` but what is the last visible line?

**Comment by jacobslusser** [comment]
`Scintilla.FirstVisibleLine + Scintilla.LinesOnScreen`. See Issue #141.

I'm not sure this is what you're looking for, but Scintilla also has ways of restricting the caret from going to close to the edge of the screen -- which could help to center your line on the screen -- but I'm not sure. You can read a little about it in the original Scintilla documentation under the topics, [SCI_SETXCARETPOLICY](http://www.scintilla.org/ScintillaDoc.html#SCI_SETXCARETPOLICY) and [SCI_SETVISIBLEPOLICY](http://www.scintilla.org/ScintillaDoc.html#SCI_SETVISIBLEPOLICY). I've never implemented these features in ScintillaNET because I honestly can't make sense of the documentation...

**Comment by Aghlara** [comment]
Thanks `LinesOnScreen` was what I was after.
