### ISSUE TITLE
More custom keyword sets and modifying operators/delimiters.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#165]
Hello, 
First of all, This is related to the issue I made a while ago: #106.

Basically, I am creating an IDE for a not very popular scripting language called PAWN, As seen in the above issue, I had trouble having custom keywords. Using that guy's help, I was able to get 1 more set so I gained exactly 2 sets, However I need more.

I was experimenting with NP++ since they use Scintilla too and I found something really interesting.
Np++ has a way to create your own syntax highlighting with your custom wordsets.
The weird thing is that there is like 8 custom keyword sets plus being able to set custom operators and delimeters.

My question is, What lexer is used there when I create such a custom language in NP++, is it like a dummy lexer ?.. if yes can it be imported to ScintillaNET ?
Would be really great if I could do that instead of using the C++ lexer.

Thanks for any help.

**Comment by JohnyMac** [comment]
Ok, I have been looking at thiis for a while and I think the best solution here is to develop a lexer, Great.

However, Can regex be used in a lexer instead of manual iterate ? If yes, Which is more efficient ?

**Comment by JohnyMac** [comment]
Bump please.

**Comment by jacobslusser** [comment]
There is no one way to write a lexer and using regular expressions is certainly acceptable. Whether it would be more efficient than iterating the lines/characters by hand? Not sure I could say. That would require profiling.

As for how Notepad++ manages to allow for custom lexers... I haven't looked into it, but I imagine that it is a custom lexer as described in [https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) but instead of having the syntax hardcoded in, it will read that from a configuration file. 

I've considered creating such a lexer for ScintillaNET, but never gotten around to it.

**Comment by JohnyMac** [comment]
So, A lexer is the only way to go..
I'll leave this issue opened for now cause I'm sure I'll have some more questions.

**Comment by JohnyMac** [comment]
Ok I've actually managed to do it myself :)

Here is the code I used: 
```c#
private void Scintilla1_StyleNeeded(object sender, ScintillaNET.StyleNeededEventArgs e)
{
	var startPos = Scintilla1.GetEndStyled();
	var line = Scintilla1.LineFromPosition(startPos);
	startPos = Scintilla1.Lines(line).Position;

	var endPos = e.Position;

	//Clear all styling.
	Scintilla1.StartStyling(startPos);
	Scintilla1.SetStyling((endPos - startPos), 0);

	//Get all text and loop through all regex matches.
	foreach (Match match in Regex.Matches(Scintilla1.GetTextRange(startPos, (endPos - startPos)), "(?:\\bTest\\b|\\bTestTwo\\b|\\bTestThree\\b)")) {
		Scintilla1.StartStyling(startPos + match.Index);
		Scintilla1.SetStyling(match.Length, 1);
	}
}
```

I'm going to close the issue now, Thanks for all your help :)
And also please if there is any problem in my code that actually might occur, Please tell me before I start doing it big.

**Comment by jacobslusser** [comment]
Looks good. :)

**Comment by JohnyMac** [comment]
Ok, I am back with a small problem.
How to setup multiline stuff with the StyleNeededEvent ?
Like for exampe, Multiline comments.

The styleNeeded event only fires with the changed set of text so the text may not contain the `/*` or `*/` so my regex will obviously fail to know its a comment... :/

Here is what happens to me: 
![Image](https://i.gyazo.com/ce3220c4cb89d167e7e6f78be96a60b4.png)

**Comment by jacobslusser** [comment]
You have to split your regex into two operations. Look for a comment start with `"/*"`. If `"*/"` is not found on the same line, store the line number in a variable. Then in the same pass of `StyleNeeded` or on a different pass, continue looking for the `"*/"` comment-end token.

Every lexer I've ever written or seen uses this same approach.

It might help to think of a line of text as not a line of text at all, but rather just a range of text that happens to end in a `"\r\n"` sequence. A good lexer will work the same whether it processes a line at a time or not.

**Comment by JohnyMac** [comment]
I see, thanks :)

btw, in a normal lexer *(non regex)*, what would be the best way to parse for stuff that are multi-character like comments.

How to check for two symbols that are after each other ?

**Comment by jacobslusser** [comment]
What I, and most lexers I've seen do, is put the lexer into a different state. For example, a lexer will start in state 0. If your scan finds a `'/'` character, it puts the lexer into state 1. We don't know yet though if this is a `"/*"` sequence, or a `"//"` sequence. 

If the next character is a `'*'` then we know it is a multi line comment and we put the lexer into state 2. The lexer continues in state 2 until it finds a `"*/"` sequence and then returns to state 0. On the other hand, if after the first `'/'` we find another `'/'`, then we know this is a single line comment and transition from state 1 to state 3. State 3 continues until we find a `"\r\n"` sequence (end of line) at which point we mark the end of the single line comment and return to state 0.

Said another way, multi character tokens (that are not keywords or identifiers) are usually broken up into multiple states. Thus, you can pause the lexer at any point in the scan -- even after the first `'/'` is found but before the next `'*'` or '`/'` character is found, and pick right back up where you left off on another pass because you set the lexer into a different state when it found that first character.

You can see this demonstrated with the string detection in the [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) recipe. Once in the string state `STATE_STRING` each pass of the lexer will continue looking for a closing `"` (double-quote) which marks the end of the string and state.

Obviously we're talking about comments and strings which are usually many, multiple characters but the same principles apply to tokens that are just two characters long, such as `"=="` or `">="`.

Finally, if for some reason the next character you find after `'/'` is NOT `'*'` or another `'/'`, then that might mean it is either a divide token (not a comment at all) or an error. For example, if the last character of the document is a `'/'` we would transition to state 1 as normal. But we might have a rule that says if the lexer finishes processing all the input and doesn't finish in the 0 state, it is an error.

There is a whole science devoted to this type of programming referred to as [state machines](https://en.wikipedia.org/wiki/Finite-state_machine).

Finally, finally, I find it helpful to remember that the text is all just a string of characters, not lines. The text actually looks like this:

```
/*\r\n\r\n\r\nhgfutgdisygft\r\nfgydsfsdf\r\ndfjsgfssdf\r\n\r\n\r\n*/
```

Treat the line breaks just like they were any other token, such as `';'` or `"=>"`, because they are!

**Comment by JohnyMac** [comment]
Ahh I see, So I have to create a global variable for storing the state and once `/` is found, set var to 1 and then on the next character, if it was `*`, Style until `*/` is found the same way and if the character was not `*`, Change the state back to zero therefore continuing to style normally.

Thanks for your effort there :)

**Comment by jacobslusser** [comment]
Just a reminder: what I described is what you would do if you were scanning character-by-character as you asked. If you are using regular expressions against an entire line of text, you could look for the complete start sequence `"/*"` because your grammar (I'm assuming) doesn't allow that sequence to be split across lines. It HAS to be completely on one line; otherwise, it's invalid.

Once that sequence is found, however, you can apply the state based approach to track it across multiple lines.

If your lexer is designed to work line-by-line instead of character-by-character, don't bother splitting the recognition of your tokens into multiple states if those tokens can't span more than one line.

**Comment by JohnyMac** [comment]
Okay another problem, How to make colorizing for keywords ?
I saw your approach in the example but the problem is that the keywords can be thousand's so I think its not good to loop on them each character ?

Probably, Its not that slow... I don't know, thats why I am asking.. ?
______________________________________________________________
`what I described is what you would do if you were scanning character-by-character as you asked`
And thats what I asked for really.. haha

I am looking forward to create a normal char-by-char lexer because I'm having some issues with the state thing in regex, And I think it would be way easier with a normal lexer.

And in fact, Just to anyone who is ever willing to create a regex lexer, Having multiple regex calls like this: 
``
 is very very slow and the codes was noticeably changing from black to colours.

**Comment by JohnyMac** [comment]
btw, I ended up using the C++ lexer and doing this to colorize more custom words: 
https://github.com/JohnyMac/ExtremeStudio/blob/b8fa924f66a23b0039fc2f4000345f1e005ef6b0/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorDock.vb#L551-L644

Basically, I handle the UpdateUI event for any changes in the UI and then recolor the visible part of code. I created my own StyleNeeded clone that can work along with a lexer.
