### ISSUE TITLE
Question : How to search multiple words using SearchInTarget

### ISSUE THREAD

**Issue by jonghewk** [jacobslusser/ScintillaNET#174]
Using the example found in the wiki, I would like to search for multiple words. 

I tried setting the SearchFlag to "regex" and  for the search text, 

I used something like "word1 | word2".

However, its not finding anything. Any suggestions?

**Comment by jacobslusser** [comment]
Sadly the native Scintilla component doesn't support alternation (` | `) in regular expressions. I would hazard a guess that it's because the built-in regular expression engine also doesn't support backtracking.

[http://www.scintilla.org/ScintillaDoc.html#Searching](http://www.scintilla.org/ScintillaDoc.html#Searching)

Future versions of Scintilla will hopefully have better regular expression support. Until then, you'll have to use .NET regular expressions. There is a performance hit using .NET regex on Scintilla, but hopefully it won't be an issue for you.

```cs
var text = scintilla.Text;
var match = Regex.Match(text, "word1|word2");
```

**Comment by jonghewk** [comment]
Thanks for the reply! 
Actually, I am looking for performance at the moment..
I will look forward to future updates. Until then, I'll use the .NET regex. 
Thanks.
