### ISSUE TITLE
AutoCCanceled event on AutoCAutoHide

### ISSUE THREAD

**Issue by igiona** [jacobslusser/ScintillaNET#196]
If the AutoCAutoHide is equal to true, the AutoC dialog disappears when the typed word does not match any of the key in the AutoC list.
The feature is actually working, by the way the 'AutoCCanceled' event is not called and there is no mean to check if the dialog is still open or not. 
This mean that the application is not able to detected if the user is still in AutoC mode or not.

**Comment by jacobslusser** [comment]
Honestly, I'm not sure whether the `AutoCCancelled` event should fire when the list closes due to a match not being found. That's not really the same as whether a user elects to close the list manually.

I believe you can get what you want, however, by checking the `AutoCActive` property. You are probably already using the `CharAdded` event to display the AutoC list... just check `AutoCActive` in that event to determine if the list is closed when a user enters a character that doesn't match and causes the list to hide.

**Comment by igiona** [comment]
Hi Jacob,

thanks for your answer.

I agree with your observation. It may not be what everybody expects.

Thanks for you input, actually I looked for such a property/function before posting. I "searched" it by surfing the entire object with the VS Intellisense, and unfortunately I did not found the property you suggested.
 I think that the reason of that VS behaviour is the fact that this property is defined with the attributes:
        [Browsable(false)]
        [EditorBrowsable(EditorBrowsableState.Never)]

Why did you decide to define them in that way?
VS does not show it as property even though is there, publicly accessible.

BTW using this property did the job for me. Thanks!

**Comment by jacobslusser** [comment]
The marking of some of the `AutoC` members with `[EditorBrowsable(EditorBrowsableState.Never)]` was a copy and paste error on my part. It has already been pointed out to me and corrected in commit 91a951af71adfc362af4d3edc8a17b1a7117c834 and will be included in the next release.

**Comment by igiona** [comment]
Okay, good to hear that.
Thank you for the support.
