### ISSUE TITLE
Add support to handle Vb.Net and C# literals

### ISSUE THREAD

**Issue by ElektroStudios** [jacobslusser/ScintillaNET#201]
Please add this feature to avoid the problem explained in the note of this other issue:

[https://github.com/jacobslusser/ScintillaNET/issues/199](https://github.com/jacobslusser/ScintillaNET/issues/199)

> Exists a numeric literal conflict as you can see in the images below, where any defined variable with the reserved name of a literal will be colored as a literal (like 'using f as Form'), I think this is due to a design issue of the suer control which does not handle literals (I think, I didn't inspected the source-code), an issue ticket should be open for this!.

![captura 2](https://cloud.githubusercontent.com/assets/13082613/13601327/7dbaf5f8-e52f-11e5-9d59-fa67a97dfc52.jpg)

Vb.Net literals (excluding "**c**" for **Char**, because Visual Studio uses the same color as a normal String):
[https://msdn.microsoft.com/en-us/library/dzy06xhf.aspx](https://msdn.microsoft.com/en-us/library/dzy06xhf.aspx)

A simple style to Test:

```
Dim literals As String = "! # % @ & i d f l r s ui ul us"

editor.Styles(Style.Vb.Keyword3).BackColor = backColor
editor.Styles(Style.Vb.Keyword3).ForeColor = Color.FromArgb(255, 181, 206, 168)
editor.Styles(Style.Vb.Keyword3).Bold = False
editor.Styles(Style.Vb.Keyword3).Italic = False
editor.Styles(Style.Vb.Keyword3).Underline = False
            
editor.SetKeywords(2, literals)
```

C# literals:
[https://msdn.microsoft.com/en-us/library/aa664674%28v=vs.71%29.aspx](https://msdn.microsoft.com/en-us/library/aa664674%28v=vs.71%29.aspx)

**Comment by robmburke** [comment]
Most likely it is the base scintilla project that handles this and getting it changed will require an act of God.  Unfortunately, the developer of Scintilla tends not to care about language-specific issues and does not generally view them as a problem worth his time; not when it comes to syntax highlighting.

I brought it to his attention that there are way too many "operators" defined for SQL.  From what I gathered, there is one list of all possible operators that are used for all languages (instead of being language specific) and there is no way to customize this list.  He, in short, said it's not worth his own time to fix it but someone else could. Considering it is a syntax highlighter, issues relating to highlighting, you would think, would be top priority and addressed; especially this simple.

Unfortunately, yours is even more complex where only a compiler would know the difference between a "variable" (f) and a literal(F). This would require some more complex lexing.  I doubt this will get fixed.  But, the best place to get an answer is the scintilla sourceforge page; the worst he can do is say no.

**Comment by ElektroStudios** [comment]
Thanks for answer.

As you mention, it is a pity that the author of Scintilla will not consider a priority the code highlighting in a control that almost the 99,9% of users use it for that purpose... more than that, it is absurd.

Hopefully you, the author of this wrapper, could do something about it, because watching your opinion explaining the priorities of the author of Scintilla I'm not motivated at all to ask him 'cause probably I will get that unwanted "NO", but anyway of course I will try...

Thanks !.

**Comment by robmburke** [comment]
I'm not the author of ScintillaNet...lol  Just someone who follows the issues board...lol.

**Comment by ElektroStudios** [comment]
Sorry my fault !!!, I didn't take coffee this morning (sorry jacoblusser )

**Comment by jacobslusser** [comment]
@robmburke is correct.

1. ScintillaNET is a wrapper around Scintilla and its lexers. The VB lexer is not implemented in ScintillaNET, it is implemented in the native Scintilla control.
2. Lexers are not parsers. To correctly determine that 'f' is a variable name and not a numeric suffix or vice versa, starts to enter the realm of parsing and understanding the source code, not simply looking for simple patterns.

That being said, I would still recommend that you open a ticket for the native Scintilla developers if you feel this is truly an issue. It doesn't hurt to try.
