### ISSUE TITLE
Example of ChangeLexerState usage

### ISSUE THREAD

**Issue by qanplazas** [jacobslusser/ScintillaNET#202]
Hello,

I'm creating lexer and I need to highlight block comments (/* */ in C#). If I'm correct, that's where ChangeLexerState API comes handy. But are there any specific rules for using that?

**Comment by jacobslusser** [comment]
Change lexer state is actually much more simplistic than that. According to the Scintilla documentation, `ChangeLexerState` is used to:
> Indicate that the internal state of a lexer has changed over a range and therefore there may be a need to redraw.

This excerpt about custom lexers also adds a little insight:
> Scintilla tries to minimize the consequences of modifying text to only relex and redraw the line of the change where possible. Lexer objects contain their own private extra state which can affect later lines. For example, if the C++ lexer is greying out inactive code segments then changing the statement #define BEOS 0 to #define BEOS 1 may require restyling and redisplaying later parts of the document. The lexer can call **ChangeLexerState** to signal to the document that it should relex and display more.

That can be somewhat vague, but my understanding is that it is essentially the same thing as `Colorize` but where `Colorize` is called by the application to restyle a portion of the document, `ChangeLexerState` is called by the lexer to do the same.

That being said, is there a reason you are creating a lexer for C# when Scintilla already has one built in?

**Comment by qanplazas** [comment]
I want to highlight $some_variable$ C# code. The regex to match it would be:`\$[a-zA-Z_][a-zA-Z0-9_]*\$`

**Comment by jacobslusser** [comment]
Going back to the original question, I don't think you'll need to utilize `ChangeLexerState` for what you're doing. To lex a multi-line, arbitrarily long token such as a block comment or multi-line string literal, you will indeed likely want to change some internal state in your lexer, but I don't see that being related to `ChangeLexerState` which is more or less a way of letting Scintilla know that some external entity has made a change to the meaning of a token in the document and it requires restyling. The example in the Scintilla documentation is perfect. Say for example, your C# code has:

```cs
#if DEBUG
// ...
#endif
```

You want to style that block differently depending on whether DEBUG is defined or not. Say you also had a project properties window in your application where users could define compiler flags and the user has changed DEBUG=0 to DEBUG=1. You would then utilize `ChangeLexerState` to let Scintilla know that it may need to restyle a range of text because the meaning of the tokens may have changed.

Should you write your own lexer? Perhaps. That would give you ultimate control. One of our users wanted to do something similar and didn't want to write a new lexer and was able to get what he needed working using the `UpdateUI` event after the lexer had made its pass. Read over issue #165 and check the code posted by @JohnyMac at the end and see if this would help save you some time.

**Comment by JohnyMac** [comment]
Hello, 

My problem was just wanting to have more wordsets, nothing else, I tried to write my own lexer but in fact, The problem was not being able to colorize multiline stuff like comments.. I spent like 20 days trying continuously but never got it right, Until I just gave up and found this better alternative (for my case) and did it.

Unless you're a programming geek and not like me, I'd recommend that you just use the Cpp Lexer and do your other small additions in the UpdateUI.

**Comment by qanplazas** [comment]
> If you don't know how to make a lexer and all that (Like me), I'd recommend that you just use the Cpp Lexer and do your other small additions in the UpdateUI using some regex searches.

Did something similar to that, works like charm. Thanks for help!
