### ISSUE TITLE
Question: Puzzled - where is the documentation?

### ISSUE THREAD

**Issue by TimMakins** [jacobslusser/ScintillaNET#212]
Hi - your wrapper is absolutely brilliant, but it is very frustrating not being able to know how to do things. The Wiki (https://github.com/jacobslusser/ScintillaNET/wiki) is a great introduction, but only gives a few examples. I am trying to find how to do tasks mentioned in the original Scintilla documentation (http://www.scintilla.org/ScintillaDoc.html). Is there a listing of all the different possibilities somewhere, as it applies to using your wrapper in Visual Studio and Visual Basic?

For example, I'd like to give an offset to the first line number, say 10000, but can't decide if such a thing is possible, or how to do it. I'd very much appreciate help, please.

**Comment by jacobslusser** [comment]
To your first question, no, there is no documentation on what enhancements ScintillaNET provides over the native Scintilla component because ScintillaNET tries not to make such enhancements. ScintillaNET tries to be a simple, pass-through wrapper. It's my opinion that such enhancements to ScintillaNET beyond Scintilla's native capabilities should be kept in extension projects or your custom application logic. This is the core library. If you are interested in understanding how the original Scintilla documentation maps to ScintillaNET the pattern is briefly described in the project README under "Conventions" here: [https://github.com/jacobslusser/ScintillaNET#conventions](https://github.com/jacobslusser/ScintillaNET#conventions).

As for line numbers, Scintilla (and thus ScintillaNET) doesn't support starting line numbers at a different offset out-of-the-box. There is a way you can fake it though by create a custom margin and then handling the display of line numbers yourself as described in the wiki article "Displaying Line Numbers" under the section "Custom Line Numbers": [https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers#custom-line-numbers](https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers#custom-line-numbers).

**Comment by TimMakins** [comment]
Sorry - I am not looking for any enhancements: I am simply trying to understand just what this wrapper is capable of, and how to do the things that are provided. Is there a list somewhere of all the different properties and methods that I can use? In my Visual Studio installation with Visual Basic, Intellisense starts to show me the different keywords and functions that I can use as I enter the letters, but it would be more helpful if there was just a list of them that I could refer to. As it is, I am just discovering them by luck!

Thanks also for answering my second question. I had seen that article, and did wonder if that was the only way. I have now converted your code to Visual Basic, and added an offset-value. Here it is, in case anyone else needs it:

TextEditor.Margins(0).Type = MarginType.RightText
TextEditor.Margins(0).Width = 35


Private Sub UpdateLineNumbers(startingAtLine As Integer)
    Dim offset As Integer = 9500
    For i As Integer = startingAtLine To TextEditor.Lines.Count - 1
        TextEditor.Lines(i).MarginStyle = Style.LineNumber
        TextEditor.Lines(i).MarginText = CStr(offset + i)
    Next
End Sub

Private Sub TextEditor_Insert(sender As Object, e As ModificationEventArgs) Handles TextEditor.Insert
    ' Only update line numbers if the number of lines changed
    If e.LinesAdded > 0 Then
        UpdateLineNumbers(TextEditor.LineFromPosition(e.Position))
    End If
End Sub

Private Sub TextEditor_Delete(sender As Object, e As ModificationEventArgs) Handles TextEditor.Delete
    ' Only update line numbers if the number of lines changed
    If e.LinesAdded < 0 Then
        UpdateLineNumbers(TextEditor.LineFromPosition(e.Position))
    End If
End Sub

**Comment by jacobslusser** [comment]
Try the Object Browser in Visual Studio. View -> Object Browser (Ctrl+Alt+J). If you've added ScintillaNET to your project you'll be able to select the ScintillaNET.Scintilla class from the tree you'll see all the method and properties and documentation for each member.

**Comment by TimMakins** [comment]
Thank, Jacob. I hadn't heard of the Object Browser before: don't know how I missed it after so long!!
