### ISSUE TITLE
ScrollRange is backwards

### ISSUE THREAD

**Issue by pstuart** [jacobslusser/ScintillaNET#213]
The docs show ScrollRange(start, end) but really the scintilla implementation is ScrollRange(secondary, primary)

where primary (the second value in .NET version will always be in view and secondary will try to be in view.

**Comment by jacobslusser** [comment]
Is your observation based on empirical evidence or a review of the documentation? Looking at the implementation I would agree with you that I've reversed the arguments in ScintillaNET (because I thought it made more sense) but I believe the correct values are still getting passed to `SCI_SCROLLRANGE` in the correct order -- start/primary in position 2, end/secondary in position 1:

```cs
public void ScrollRange(int start, int end)
{
    var textLength = TextLength;
    start = Helpers.Clamp(start, 0, textLength);
    end = Helpers.Clamp(end, 0, textLength);

    // Convert to byte positions
    start = Lines.CharToBytePosition(start);
    end = Lines.CharToBytePosition(end);

    DirectMessage(NativeMethods.SCI_SCROLLRANGE, new IntPtr(end), new IntPtr(start));
}
```

Am I wrong?

I've said before that ScintillaNET tries only to be a pass-through wrapper for the native Scintilla, but there are of course exceptions.

**Comment by pstuart** [comment]
Well, the code looks right, but the empirical evidence suggests otherwise, if I do a scrollRange(15,50) it will only bring 15 to the bottom, however, doing a scrollRange(50,15) will bring 15 to 50 into view.

So maybe it is my understanding of it that is backwards.  I think you chose wisely to implement it start, end even though scintillas docs show SCI_SCROLLRANGE as end,start. 

But maybe its my understanding of how its supposed to work?

**Comment by jacobslusser** [comment]
I agree with you. Thanks for pointing that out!
