### ISSUE TITLE
Change Margin Color on Line Number

### ISSUE THREAD

**Issue by PUSRISTEK** [jacobslusser/ScintillaNET#220]
This is my code on form load event, codeeditor is scintillaNET control.

CodeEditor.SetFoldMarginColor(true,Color.Blue);
CodeEditor.SetFoldMarginHighlightColor(true, Color.Blue);

but the margin color won't change. why?

**Comment by jacobslusser** [comment]
Part of your confusion is my fault for not doing a better job to explain margin colors, but most of this is Scintilla's fault. The way it handles margins--especially when it comes to color--is insanely difficult to understand. Before going any further, read these links:

The intro to Margins in the original Scintilla documentation:
[http://www.scintilla.org/ScintillaDoc.html#Margins](http://www.scintilla.org/ScintillaDoc.html#Margins)

> The margins are numbered 0 to 4. Using a margin number outside the valid range has no effect. By default, margin 0 is set to display line numbers, but is given a width of 0, so it is hidden. Margin 1 is set to display non-folding symbols and is given a width of 16 pixels, so it is visible. Margin 2 is set to display the folding symbols, but is given a width of 0, so it is hidden. Of course, you can set the margins to be whatever you wish.

The comments at the top of this code snippet:
[https://www.garybeene.com/code/gbsnippets_gbs_00635.htm](https://www.garybeene.com/code/gbsnippets_gbs_00635.htm)
```
'By default, margins 0-2 are given the following width and display attributes. A margin
'with zero width is not displayed.
'    margin      display      width
'      0        line numbers    0  (not visible)
'      1        symbols         16 (visible)
'      2        symbols         0  (not visible)
```
```
'Setting margin FG/BG colors is handled differently depending on the type of margin.
'Line Number Margin          - FG/BG color defined by Style_LineNumber
'Text Margin                 - BG color defaults to Style_LineNumber BG color
'Symbol Margin (non-folding) - defaults to Syle_Default FG/BG colors. Use SC_Margin_Back/Fore to change.
'Symbol Margin (folding)     - defaults to system 3DFace/3DHighLight colors. Change with SetFoldMarginColour/SetFoldMarginHiColor
```

And finally, the comments on the `Style.LineNumber` constant in ScintillaNET:
```cs
/// <summary>
/// Line number style index. This style is used for text in line number margins. The background color of this style also
/// sets the background color for all margins that do not have any folding mask set.
/// </summary>
public const int LineNumber = NativeMethods.STYLE_LINENUMBER;
```

Obvious isn't it? LOL...

Translating... when you drop a new Scintilla control on your form margin `1` is displayed by default, and it is configured as a symbol margin and uses a mask which allows any symbol. Thus the `SetFoldMarginColor` and `SetFoldMarginHighlightColor` APIs will have no effect because this is not a 'fold' margin. It is a standard `MarginType.Symbol`. Let's verify that by enumerating the margins:

```cs
Debug.WriteLine("Margins:");
foreach (var margin in scintilla.Margins)
{
    Debug.WriteLine("Index: " + margin.Index + ", Type: " + margin.Type + ", Width: " + margin.Width + ", Mask: 0b" + Convert.ToString(margin.Mask, 2));
}
```

The output is:
```
Margins:
Index: 0, Type: Number, Width: 0, Mask: 0b0
Index: 1, Type: Symbol, Width: 16, Mask: 0b1111111111111111111111111
Index: 2, Type: Symbol, Width: 0, Mask: 0b0
Index: 3, Type: Symbol, Width: 0, Mask: 0b0
Index: 4, Type: Symbol, Width: 0, Mask: 0b0
```

Since margin `1` is what we're seeing on a new control, and it is a symbol margin, we can change the background color using either `Style.Default` or `Style.LineNumber`... depending on the way the margin mask is set up. Without having to understand the way masking works we can verify that by using this code:

```cs
// One of these will change the background color of margin 1
scintilla.Styles[Style.LineNumber].BackColor = Color.Red;
scintilla.Styles[Style.Default].BackColor = Color.Red;
```

Or better still, if setting the fold margin was truly your intention we can verify that by hiding the default margin `1`, showing margin `2` and then using `SetFoldMarginColor` and `SetFoldMarginHighlightColor`:

```cs
// Hide the default margin
scintilla.Margins[1].Width = 0;

// Show the fold margin and configure it as a fold margin
scintilla.Margins[2].Width = 16;
scintilla.Margins[2].Mask = Marker.MaskFolders;

// Set the fold margin colors
scintilla.SetFoldMarginColor(true, Color.Blue);
scintilla.SetFoldMarginHighlightColor(true, Color.Blue);
```

NOTE: You'll see that I also manually set the margin `Mask` to be a fold margin, because the Scintilla documentation lies. Margin `2` is not properly configured as a fold margin and you can see that based on our enumeration of the margin defaults above.

Finally, if you want a margin that is not a fold margin (which uses `SetFoldMarginColor` and `SetFoldMarginHighlightColor`) and not a line number or text margin (which uses `Style.LineNumber` for both foreground and background or just background) you can actually change the margin type to either `MarginType.BackColor` or `MarginType.ForeColor` which is like changing a margin to be a symbol margin, but forces it to also use the background or foreground color of `Style.Default`:

```cs
scintilla.Margins[1].Width = 16;
scintilla.Margins[1].Type = MarginType.ForeColor;
scintilla.Styles[Style.Default].ForeColor = Color.Orange;
```

Phew!

You might also find some interesting information in these recipes. They don't talk about margins directly, but may give you additional insight.
- [https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers](https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers)
- [https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines)
- [https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding)

**Comment by jacobslusser** [comment]
FYI [ScintillaNET v3.6.3](https://github.com/jacobslusser/ScintillaNET/releases) brings support for additional margins beyond the limit of 5 and support for more background color options.

**Comment by MrBearPaw** [comment]
https://icryptic.net/r/W511.png

Image shows that the application uses a ScintillaNET i just wanna know how they put numbers besides it and change background color.
When i use Scintilla and change the background color it stays as white then when i click it it changes the color.
can you please tell me a the code shown in the image where Numbers in the side shows up like fastcoloredtextbox and also how to change the background of scintilla?
Thanks

**Comment by MrBearPaw** [comment]
> FYI [ScintillaNET v3.6.3](https://github.com/jacobslusser/ScintillaNET/releases) brings support for additional margins beyond the limit of 5 and support for more background color options.

https://icryptic.net/r/W511.png

Image shows that the application uses a ScintillaNET i just wanna know how they put numbers besides it and change background color.
When i use Scintilla and change the background color it stays as white then when i click it it changes the color.
can you please tell me a the code shown in the image where Numbers in the side shows up like fastcoloredtextbox and also how to change the background of scintilla?
Thanks
