### ISSUE TITLE
How to handle keypresses such as "CTRL+G" without passing it to ScintillaNET. 

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#221]
Currently, I have this code: 
```
Private Sub Editor_KeyDown(sender As Object, e As KeyEventArgs) Handles Editor.KeyDown
      If e.Control = True And e.KeyCode = Keys.G Then
            Dim frm as New GotoForm()
            frm.ShowDialog()
            e.SuppressKeyPress = True
        End If
    End Sub
```

However, Everytime I press CTRL+G, The dialog does show but at the same time something like a *[BEL]* shows in the editor: 
![The Img](https://i.gyazo.com/d660307c56c3b51193ac3e46bc39f348.png)

**Comment by robmburke** [comment]
@JohnyMac Here is your answer: #101 and the code about ProcessCmdKey is what you want to deal with.

Here it is again @jacobslusser   lol.
I really think something like #205 needs to be done as a setting that overrides ProcessCmdKey that keeps the editor window from getting a hold of those keypresses and processing them.  Doing this will not ruin the CTRL command itself as far as the person's program is concerned, it just keeps Scintilla from taking it in.  You can still even assign custom Scintilla commands to them.

If someone really wants them (which I can't believe anyone wants those little symbols in their code editor), they can figure out how to get them since I would really like to believe they are the minority.

**Comment by JohnyMac** [comment]
I don't quite get it.. Where do I have to override that event/function ?
Its not a part of Scintilla as I can see.

**Comment by robmburke** [comment]
It's a built in method in the Window.  This stops the Window from passing that key combination into Scintilla, but allows you to handle it within that code block.

**Comment by JohnyMac** [comment]
I tried it.. Placed a breakpoint in it.. Its never even called.. :/

I overloaded it in the form where I have ScintillaNET, right ?

**Comment by JohnyMac** [comment]
It works.. Not perfect though.. There is another problem: 

```
    Protected Overrides Function ProcessCmdKey(Byref msg As Message, keyData As Keys) As Boolean
        If (keyData And (Keys.Control Or Keys.G)) > 0 Then
            Dim frm as New GotoForm()
            frm.ShowDialog()
            Return True
        Else If (keyData And (Keys.Control Or Keys.S)) > 0 Then
            MainForm.SaveFile(Editor)
            Editor.SetSavePoint()
            If (keyData And ((Keys.Control Or Keys.Shift) Or Keys.S)) > 0 Then 'If he has shift pressed also.
                MainForm.SaveAllFiles(Me, EventArgs.Empty)
            End If
            Return True
        Else
            Return MyBase.ProcessCmdKey(msg, keyData)
        End If
    End Function
```

Basically, Pressing ANY key will pass that IF so the goto dialog will always show.. :/
Ik its most likely my translation skills that are bad.. :P

**Comment by JohnyMac** [comment]
Hello ?

**Comment by JohnyMac** [comment]
oops, forgot to close.
