### ISSUE TITLE
guillemet word character ? 

### ISSUE THREAD

**Issue by larsvoigt** [jacobslusser/ScintillaNET#234]
Hi @jacobslusser ,
we are using scintillaNET for some years now. 
It works like a charm. Great project!

But at this point is not reallly clear if it works right or works wrong.
The cursor stand on  ``` »Mons|ieur« ``` than call 
``` GetWordFromPosition() ``` and get ``` »Monsieur« ```.
It return the word + the Guillemets.  But only the word was expected.
For me the question is: Are Guillemets word character?

Thanks Lars

**Comment by jacobslusser** [comment]
The `GetWordFromPosition` method should only match characters specified in the `WordChars` property. Have you changed the default value of that property?

**Comment by larsvoigt** [comment]
No, I haven`t changed this property. I´m not aware this even exists.

**Comment by larsvoigt** [comment]
Hmm It seems as if the native scintila deliver the same result. 
I have make a test with Notepad++.
The cursor is also placed on ``` »Mons|ieur« ``` than I open the find dialog and 
 the input field will be autofill  with ``` »Monsieur« ``` instead of  ``` Monsieur ```.

<img src="https://cloud.githubusercontent.com/assets/8373218/15419112/2f2168c8-1e64-11e6-93b7-ccc9f1240808.PNG" alt="alt text" width="70%" height="70%">

**Comment by jacobslusser** [comment]
I became curious about this and so did some heavy debugging into native Scintilla code. Basically, the search for a word start or end comes down to these functions:

```cpp
CharClassify::cc Document::WordCharClass(unsigned char ch) const {
	if ((SC_CP_UTF8 == dbcsCodePage) && (!UTF8IsAscii(ch)))
		return CharClassify::ccWord;
	return charClass.GetClass(ch);
}

/**
 * Used by commmands that want to select whole words.
 * Finds the start of word at pos when delta < 0 or the end of the word when delta >= 0.
 */
int Document::ExtendWordSelect(int pos, int delta, bool onlyWordCharacters) {
	CharClassify::cc ccStart = CharClassify::ccWord;
	if (delta < 0) {
		if (!onlyWordCharacters)
			ccStart = WordCharClass(cb.CharAt(pos-1));
		while (pos > 0 && (WordCharClass(cb.CharAt(pos - 1)) == ccStart))
			pos--;
	} else {
		if (!onlyWordCharacters && pos < Length())
			ccStart = WordCharClass(cb.CharAt(pos));
		while (pos < (Length()) && (WordCharClass(cb.CharAt(pos)) == ccStart))
			pos++;
	}
	return MovePositionOutsideChar(pos, delta, true);
}
```

Based on my research the key to understanding this is in the `WordCharClass` method. If you want you can dig into the `CharClassify` class and enumeration values, but you don't really need to to understand what's going on. The `if` statement at the top basically says: if UTF8 (which we are) and not an ASCII value -- char less that `0x80` (which `»` and `«` are not) then classify it as a "word" character.

Said another way, it would seem that Scintilla considers anything beyond the standard ASCII characters to be a word character and that would include Guillemets.

In theory, however, it is possible to get Scintilla to behave the way you want. The `WordChars` property is actually just one property implemented but Scintilla exposes a few similar ones for whitespace and punctuation. See [http://www.scintilla.org/ScintillaDoc.html#SCI_SETWORDCHARS](http://www.scintilla.org/ScintillaDoc.html#SCI_SETWORDCHARS):

These APIs are very picky/buggy though and I've had mixed results with them and hence never implemented whitespace or punctuation characters. They are also limited to single-byte UTF-8 characters and so while the Guillemets *might* work, other Unicode punctuation will certainly not. Changing these defaults can also have very undesirable effects down the road with other Scintilla functions.

Since these APIs are not currently implemented you would need to implement them yourself if you are interested in using them. My advice in this case would be to simply drop (or rather, stay) in .NET and use the powerful .NET regular expressions or string functions at your disposal to find the word boundaries instead of Scintilla in this case.

**Comment by larsvoigt** [comment]
Hi @jacobslusser,
 many thanks that you debugging this issues and for your hits to solve the problem.
But we think, it is a bug and the scintilla guys should have a look on it.
So I have also posted the problem on the [scintilla bug tracker](https://sourceforge.net/p/scintilla/bugs/1832/).

**Comment by jacobslusser** [comment]
Over at the Scintilla bug tracker, it looks like the answer you got is kinda what I expected. TL;DR; If the character you want to include/exclude from the list of word characters is ASCII you can use the Scintilla APIs I mentioned above to make that change. If the character(s) in question are Unicode, you're out of luck.

Unfortunately Scintilla's Unicode support is pretty weak... but I still think using .NET's ability to get what you want is not only necessary (as the Scintilla team pointed out) but even better IMO. I would be happy to help you work on the regular expression or whichever other technique you would like to pursue.
