### ISSUE TITLE
Making scintilla.Styles assignable?

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#24]
So, let's say you made `scintilla.Styles` not just readonly?  This would allow people to create their own `StyleCollection()` as an object and then simply assign that object to `scintilla.Styles`.

Does that sound like a reasonable idea?  Is there a major reason that that would be impossible?

If this is doable, my ultimate goal was to take any of the user-rolled themes that may end up in the Wiki (or any I create for my project) and start adding them to a "managed" DLL of styles that someone can simply include in their project through nuGet to have access to predefined styles for different languages without having to copy/paste examples from the wiki if they didn't care about customizing it themselves.  In essence, making a "companion" package to Scintilla that has Scintilla has a prereq. And everything would be simpler if I could just assign the resultant `StyleCollection` to the `scintilla.Styles` property.

`Managed DLL:`
```
namespace Serysoft.ScintillaNET.Syntax
{
    public class Styler
    {
        private Highlighter highlighter;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="language"></param>
        /// <param name="theme"></param>
        public Styler(Languages language, Themes theme)
        {
            switch (language)
            {
                case Languages.Cpp:
                    highlighter = new Cpp(theme);
                    break;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="scintilla"></param>
        public void Set(Scintilla scintilla)
        {
            scintilla.Lexer = highlighter.Lexer;
            scintilla.SetKeywords(0, highlighter.Keywords[0]);
            scintilla.Styles = highlighter.Theme;
        }
    }

    public class Cpp : Highlighter
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="theme"></param>
        public Cpp(Themes theme)
        {
            base.Lexer = Lexer.Cpp;
            base.Keywords = this.Keywords;

            switch (theme)
            {
                case Themes.Light:
                    base.Theme = this.Light;
                    break;

                case Themes.Dark:
                    base.Theme = this.Dark;
                    break;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        private List<string> Keywords
        {
            get
            {
                List<string> list = new List<string>();

                list.Add("keywords");

                return list;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        private StyleCollection Light
        {
            get
            {
                StyleCollection styles = new StyleCollection(new Scintilla());

                styles[Style.Cpp.String].ForeColor = Color.Red;

                return styles;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        private StyleCollection Dark
        {
            get
            {
                throw Exceptions.DarkNotImplemented;
            }
        }
    }
}
```

`Code Implementation:`
```
Styler styler = new Styler(Languages.Cpp, Themes.Light);
styler.Set(code);
```

**Comment by jacobslusser** [comment]
Technically what you're suggesting is probably possible, but in practice it’s much harder that you might realize; because when you disconnect the `StyleCollection` you're really disconnecting the styles. To do that we would need to store every style property locally so that when you eventually marry the `StyleCollection` and the `Scintilla` control you can then push all the style properties you had previously stored locally to the `Scintilla` control. In an earlier iteration of ScintillaNET I pursued an idea like this and gave up on it because it seemed like a lot of work for a little gain. In the end I decided to “*accept the original Scintilla API for what it is and not try to coerce it into a .NET-style API when it should not or could not be*" as noted in the project [README.md](https://github.com/jacobslusser/ScintillaNET/blob/master/README.md).

Now, that being said I think there is still a way to do what you want without having to separate the styles and `StyleCollection`. Essentially you want a wrapper class that will make it possible to set the lexer and styles in one easy property and there is no reason you still couldn't do something like that. 
I think if you modified your example to pass the `Scintilla` argument in the `Styler.Set` method to the `Highlighter`, the `Highlighter` could do the work of setting the styles--without first having to store them locally:

```cs
namespace Serysoft.ScintillaNET.Syntax
{
    public class Styler
    {
        private Highlighter highlighter;

        public Styler(Languages language, Themes theme)
        {
            switch (language)
            {
                case Languages.Cpp:
                    highlighter = new Cpp(theme);
                    break;
            }
        }

        public void Set(Scintilla scintilla)
        {
            // Rather than 'apply' the data stored in the Highlighter, pass control to it
            highlighter.Set(scintilla);
        }
    }

    public class Cpp : Highlighter
    {
        public Cpp(Themes theme)
        {
            base.Theme = theme;
        }

        private List<string> Keywords
        {
            get
            {
                List<string> list = new List<string>();

                list.Add("keywords");

                return list;
            }
        }

        internal void Set(Scintilla scintilla)
        {
            // This is where a highlighter configures Scintilla the way it wants to
            scintilla.Lexer = Lexer.Cpp;
            scintilla.SetKeywords(0, Keywords[0]);
            
            switch(theme)
            {
                case Themes.Light:
                    scintilla.Styles[Style.Cpp.Comment].ForeColor = Color.Green;
                    scintilla.Styles[Style.Cpp.Number].ForeColor = Color.Blue;
                    // etc..
                    break;
                    
                case Themes.Dark:
                    throw Exceptions.DarkNotImplemented;
                    break;
            }
        }
    }
}
```
