### ISSUE TITLE
New beginner's problem! Lexer do not work

### ISSUE THREAD

**Issue by gaby1989** [jacobslusser/ScintillaNET#267]
I simply  build a new winform project, add scintillaNET.dll to ToolBox, drag the box onto the Form1, change the Lexer option to 'CPP'. To Run the form, the text is not styled. Why is it?

**Comment by gaby1989** [comment]
Here is the attachings.
![qq 20160725113032](https://cloud.githubusercontent.com/assets/20633550/17089655/7b4b05a8-525b-11e6-82a6-09148d8762c1.png)

**Comment by gaby1989** [comment]
Attaching 2! Help me please! Thanks!
![qq 20160725113123](https://cloud.githubusercontent.com/assets/20633550/17089676/9df1bfac-525b-11e6-9787-968a78509d27.png)

**Comment by OrkhanAlikhanov** [comment]
What about reading [documentation](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)?

**Comment by jacobslusser** [comment]
Yes, as @OrkhanAlikhanov has pointed out, the documentation is your friend...

In fact, if you have set the `Lexer` property then Scintilla is actually lexing your document and performing syntax highlighting... it's just that you can't see it because you haven't defined the way that syntax highlighting should appear (font, color, etc...). You've missed that second important step of defining the styles.

**Comment by gaby1989** [comment]
Thanks!
I have been used to scintillaNET 2.6 for a long time. I decide to relearn your amazing 3.X!

**Comment by SamAltrax** [comment]
THANK U SO MUCH FINNALY
