### ISSUE TITLE
Question: using caret in Auto complete 

### ISSUE THREAD

**Issue by Hadirj** [jacobslusser/ScintillaNET#281]
In old version of ScintillaNet I used Snippets as below:

`Snip.Add(new Snippet("for", @"for (var i=0 ; i < $length$ ; i ++){}"));`

where cursor will be moved to $length$ when user uses this (for) snippet. how can I achieve same result in Auto Complete.

**Comment by jacobslusser** [comment]
There is no native support for snippets in v3. You would need to use one of the key bindings to listen for the snippet key combination of your choice and then insert the text. [https://github.com/jacobslusser/ScintillaNET/wiki/Key-Bindings](https://github.com/jacobslusser/ScintillaNET/wiki/Key-Bindings)

After insertion, you can select the macro values and move the caret into the desired position using any combination of:
`Scintilla.CurrentPosition` and `Scintilla.AnchorPosition`
`Scintilla.SetSel`
`Scintilla.SelectionStart` and `Scintilla.SelectionEnd`
etc...

Since many snippets have the same 'macro' values in numerous places and you want them all to update at the same time you'll probably want to select all the values at once using multiple selections.
[https://github.com/jacobslusser/ScintillaNET/wiki/Rectangular-and-Multiple-Selections](https://github.com/jacobslusser/ScintillaNET/wiki/Rectangular-and-Multiple-Selections)
