### ISSUE TITLE
Degenerate performance in CharToBytePosition

### ISSUE THREAD

**Issue by jonandr** [jacobslusser/ScintillaNET#283]
Hi,

Using my Scintilla.NET-based editor I tried to open a file which consisted of a single line of roughly 200 000 characters, which promptly locked up the entire program. I suppose this is not a normal use case, but it is not entirely unheard of (this particular file was a JSON response from an API).

I investigated and saw that this was due to the piece of code in the editor which highlights links, which works like the "Find and Highlight Words" guide in the wiki.

Any time you use SearchInTarget you have to set TargetStart and TargetEnd a bunch of times, which looks innocent enough. However, each assignment of TargetStart/End causes calls to CharToBytePosition which in turn causes a huge number of SCI_POSITIONRELATIVE messages to be sent if there are long lines in the range.

If x is the length of the line, then CharToBytePosition causes x calls to SCI_POSITIONRELATIVE:

```c#
while (pos > 0)
{
	// Move char-by-char
	bytePos = scintilla.DirectMessage(NativeMethods.SCI_POSITIONRELATIVE, new IntPtr(bytePos), new IntPtr(1)).ToInt32();
	pos--;
}
```

It seems to me like you could just move _pos_ characters forward in one go but maybe there is some edge case I'm overlooking:

```c#
bytePos = scintilla.DirectMessage(NativeMethods.SCI_POSITIONRELATIVE, new IntPtr(bytePos), new IntPtr(pos)).ToInt32();
```

**Comment by jacobslusser** [comment]
If you search the forums here you'll find a few similar discussions about this. What it boils down to is that Scintilla only understands UTF-8, which is a variable-length encoding. What that means is that if you want set your target start to the 5th character say, that could be at byte 5 or all the way at byte 7 or byte 10, depending on which characters you're stepping over. UTF-8 could encode a character as 1 byte, but depending on the character also encode it as 2 bytes or more. Put another way, 5 characters does not always equal 5 bytes.

No offense to my fellow .NET developers but this subtle difference is lost on most of them. They expect position 5 to be character 5 and if it is not, it's like gravity has ceased to exist.

To make the ScintillaNET API work like .NET developers expect we internally maintain a lookup list so that when someone asks for the character at position 5 we know that it is actually at byte position 7 (or whatever). This lookup is highly optimized, but as you found out, it has a weakness.

To maintain a lookup for every single character would be a HUGE performance impact so we instead maintain a pointer for the *start of every line*. This works pretty well because we can do those translations pretty quickly by first looking up the translation to the line start and then counting the number of characters/bytes in on that line to get the final requested value.

That scheme doesn't work, however, when someone has extremely long lines because it can't leverage any of the cached line offsets. There aren't any because there is only one long line in the document. Since counting always starts at the beginning of the line... well, as you can see, each translation is doing an excessive amount of counting.

For that reason many text editors will not try to do syntax highlighting or searching beyond a certain line length. You could try and add a similar restriction to your app, but as for ScintillaNET I don't think there is an optimization I could do that would get you what you want. The other 99.99% of text files have reasonably length lines and that is what it is tuned for.

**Comment by jonandr** [comment]
Thanks for the explanation.
