### ISSUE TITLE
Comment and Uncomment [Question]

### ISSUE THREAD

**Issue by autovaton** [jacobslusser/ScintillaNET#286]
Is there an equivalent to the old Scintilla.Lexing.LineComment() and Scintilla.Lexing.LineUncomment() methods?   I do not see a way to add a label to mark this as a question.

**Comment by jacobslusser** [comment]
Short answer, no. We're trying to stay very close to the feature set offered by the native Scintilla component and not go beyond that where possible. Since this is not a native feature, we don't support it.

With more time though I could show you some simple ways to accomplish this. It wouldn't be hard.

**Comment by autovaton** [comment]
Thanks for the input. I wrote some code to make it work.
