### ISSUE TITLE
Code folding with JSON data

### ISSUE THREAD

**Issue by joxi** [jacobslusser/ScintillaNET#294]
Hi,

I have been using Scintilla.NET in my app for some time now and it's great. Recently I tried to enable code folding, but I have problems when displaying JSON (no problems with XML). It seems that code folding works correctly only for the part of the Scintilla control that is visible on the form; immediately after I scroll down to display data not visible initially, code folding markers are missing or closing marker lines point to the incorrect line and thus only part of json node is closed when collapsed.
I have composed a small Windows Forms project so you can try it; execute it, click button 'Load JSON' to obtain json data from public testing web service and display it in Scintilla with code folding enabled.
Used Scintilla version 3.5.10, application targets .NET 4.5.
[Scintilla JSON.zip](https://github.com/jacobslusser/ScintillaNET/files/651967/Scintilla.JSON.zip)

**Comment by jacobslusser** [comment]
This is some kind of quirk of Scintilla or the JSON lexer. I can only speculate that it is optimized to only parse the text in view and there is a bug that does not (re)parse text which is scrolled into view after the initial pass.

I had a hunch that seems to work and I added a line to your source just after the text is loaded:

```cs
_scintilla.Text = ObtainData("https://jsonplaceholder.typicode.com/users");
_scintilla.Colorize(0, _scintilla.TextLength);
```

What the call to `Colorize` does is ask Scintilla to run the lexer/parser across the range provided so that you will have syntax highlighting -- even if that text is not in view. This seems to have the desired effect of identifying the fold points as well for the JSON which is outside of the initial view.

**Comment by joxi** [comment]
I've added this line to my app and it seems to work (tried on couple of JSON samples). Thx.

At the moment I have added call to Colorize to my base viewer class so it is executed for every lexer (I am also displaying XML, HTML and CSS with Scintilla). Should I ensure that Colorize is executed only with JSON? Can there be any performance penalties (or some other problems) calling Colorize for every lexer? What do you recommend?

**Comment by joxi** [comment]
I have tested now with large JSON data (25 MB) and it takes twice as time to display data when calling Colorize so I changed code to call Colorize only with JSON data and when user has code folding enabled.
Since JSON files are usually not that large this shouldn't be a big problem for my app.

**Comment by jacobslusser** [comment]
I've never seen this issue with the other lexers, so I would start by only doing the extra work when using the JSON lexer and see if that's all you need.
