### ISSUE TITLE
Accept strings containing nulls?

### ISSUE THREAD

**Issue by pg94au** [jacobslusser/ScintillaNET#298]
From what I've seen from testing on my own, the ScintillaNET control does not accept null characters in strings.

If I set the `Text` property to a value like `"abc\0def"`, the control does not display anything beyond `"abc"`.  If I open a file containing null bytes in Notepad++ and copy and paste to the ScintillaNET control, the NUL characters are replaced by spaces (0x20).

Is there a way to get ScintillaNET to work with null bytes in the content?

**Comment by jacobslusser** [comment]
The native Scintilla control supports `NUL` characters and I *thought* we did also. What is probably happening is that the `Text` property internally uses one of the Scintilla APIs that sees `NUL` as the end of the string. Try another API such as `AppendText` or `InsertText` and let me know what you find.

**Comment by pg94au** [comment]
`AppendText` does display the entire string, with the 0 byte displayed as `NUL`.

`InsertText` does not.  Also, copying and pasting a text block containing a null also does not preserve the null.  It is translated to a space.

Thanks for your help.

**Comment by jacobslusser** [comment]
For future reference for anyone else (and myself), this boils down to how the Scintilla API is set up. In some instances it will accept C-style null-terminated strings. In others APIs, strings are length specified.

Example null-terminated APIs:
- [SCI_SETTEXT](http://www.scintilla.org/ScintillaDoc.html#SCI_SETTEXT) - which cooresponds to [Text](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L5009-L5021) setter
- [SCI_INSERTTEXT](http://www.scintilla.org/ScintillaDoc.html#SCI_INSERTTEXT) - which cooresponds to [InsertText](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L1288-L1304)

Example length specified APIs:
- [SCI_APPENDTEXT](http://www.scintilla.org/ScintillaDoc.html#SCI_APPENDTEXT) - which cooresponds to [AppendText](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L157-L162)

There are others if anyone else wants to document them.

For loading large strings, the best (although most complicated) way is still probably [Background Loading](https://github.com/jacobslusser/ScintillaNET/wiki/Documents#background-loading) which has the benefit of being accessible from a background thread *and* supports `null` characters because it is length-based.
