### ISSUE TITLE
Disabling zoom

### ISSUE THREAD

**Issue by tryashtar** [jacobslusser/ScintillaNET#313]
I want to disable zooming in my Scintilla textbox. I tried using the `ZoomChanged` event like so:

    private void TryZoom(object sender, EventArgs e)
    {
        Scintilla box = sender as Scintilla;
        box.Zoom = 0;
    }

Of course, this recurses forever and overflows. Other than doing some bad manual solution, how would I disable zooming? Thanks

**Comment by jacobslusser** [comment]
Remove the key bindings. [https://github.com/jacobslusser/ScintillaNET/wiki/Key-Bindings](https://github.com/jacobslusser/ScintillaNET/wiki/Key-Bindings)

**Comment by tryashtar** [comment]
Yes, I took a look at those, but I don't see a key definition for scrolling up/down with the scroll wheel.

**Comment by tryashtar** [comment]
In fact, even `ClearAllCmdKeys()` doesn't disable zooming with CTRL+scrollwheel, so is there another way to disable that action?

**Comment by jacobslusser** [comment]
I'm not aware of any built-in way to disable `CTRL`+`WHEEL` zooming. So your only option would be to go around Scintilla's native abilities to implement this.

I would imagine it would be possible to subclass the `Scintilla` control class and handle the `OnMouseWheel` event, determine if the `CTRL` key is pressed, and suppress the message so that the native Scintilla component does not respond to it. It may be necessary, however, to drop down even further and handle the `WM_MOUSEWHEEL` message in the `WndProc` method.

**Comment by tryashtar** [comment]
Alright, thanks for your help.

**Comment by francaru** [comment]
```csharp
private void scintillaBox_ZoomChanged(object sender, EventArgs e)
{
     if(scintillaBox.Zoom != 0) // If the Zoom level is different than the default
     {
          scintillaBox.Zoom = 0; // Set the Zoom level to default
     }
     else
     {
          // continue...
     }
}
```
