### ISSUE TITLE
Syntax highlighting for keywords that don't have whitespace/etc

### ISSUE THREAD

**Issue by domdarnus** [jacobslusser/ScintillaNET#315]
I think I saw an issue like this similar before...
But basically;

When I set a keyword like so:

`box.SetKeywords(0, "table this game");
`

And let's say in my box, I have the following text:

```
print(table.test)
print(game)
print(this.test)
```

Only the "game" keyword is highlighted. The "table" and "this" keywords are not, even though they should be. It seems that the keyword is only hightlighted if it is followed by whitespace, or something like that (closing parentheses), but not for periods or dots?

Is there any fix for this, or any way I could go around this?

**Comment by jacobslusser** [comment]
You might be looking for the `WordChars` property. This determines what is considered a "word" and what isn't. It could be that the `.` is being considered part of the word and thus your keywords don't match, e.g. `table.test` doesn't match `table`.

**Comment by domdarnus** [comment]
I printed out the items in the WordChars property of my text editor and I got the following:
`zyxwvutsrqponmlkjihgfedcba_ZYXWVUTSRQPONMLKJIHGFEDCBA9876543210`

The `.` isn't in there, so I don't think that is the issue. Just in case, I also tried setting the WordChars property to my own set of letters:

`box.WordChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";`

The issue remained and I also found out something else:

I tested it out on the keyword `Test123` and that seemed to get highlighted, even though it had numbers which weren't in my WordChars property, so that suggests the WordChars property doesn't have much effect.

**Comment by jacobslusser** [comment]
This could be an issue with the lexer you're using. Is this one of the built-in lexers? Which one? Is the code you're trying to syntax highlight actually that language or something else?

**Comment by domdarnus** [comment]
I'm using the built-in lexer for Lua. The code I'm trying to syntax highlight is correct (Lua indexes tables like so: 

`local table1 = {["test"] = 5} print(table1.test)`
`> output: 5`

I do not touch with any syntax-changing-functions (if there even are any). All I do in my code is change the colors/etc, based on this guide, using the proper values: https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting

**Comment by jacobslusser** [comment]
Each Scintilla lexer is a little different and has its own quirks. In this case, it appears that the Lua lexer is designed to use built-in objects and their respective functions as a single keyword. e.g. instead of `table` and `insert`, the keyword list should include `table.insert` as a single keyword.

For anyone wondering how I arrived at this knowledge, I learned it by studying the SciTE .properties files and/or the Lua lexer source code in Scintilla. 
[https://sourceforge.net/p/scintilla/scite/ci/rel-3-7-3/tree/src/lua.properties](https://sourceforge.net/p/scintilla/scite/ci/rel-3-7-3/tree/src/lua.properties)
[https://sourceforge.net/p/scintilla/code/ci/rel-3-7-3/tree/lexers/LexLua.cxx](https://sourceforge.net/p/scintilla/code/ci/rel-3-7-3/tree/lexers/LexLua.cxx)

For your convenience, I put all this into a sample Gist.
[https://gist.github.com/jacobslusser/91a3a00ec8eb52ea238ee7c18c8cdf99](https://gist.github.com/jacobslusser/91a3a00ec8eb52ea238ee7c18c8cdf99)

**Comment by domdarnus** [comment]
Ah I see. So there is no way to do syntax highlighting for a keyword in which it's members are not known until run-time?

One option would somehow be to modify the current Lua lexer but that would be extremely complicated.

**Comment by jacobslusser** [comment]
If you dump the `DescribeKeywordSets` method at runtime you'll see that the Lua lexer supports several other user-defined keyword sets:

```
Keywords
Basic functions
String, (table) & math functions
(coroutines), I/O & system facilities
user1
user2
user3
user4
```

These correspond to additional `Style.Lua.Word*` constants that I have not used in my sample, but are available.

In theory, you can add additional keywords (variable names and members parsed at runtime), add them to one of the `user*` keyword sets and then call `ChangeLexerState` to let the lexer know that you have updated the keyword list and get those things highlighted. However, to know the names of variables, members, etc... would require parsing and understanding the actual code and that is something Scintilla(NET) can NOT do. You're on your own for that. But in essence that is how you would highlight words that are not language constants.
