### ISSUE TITLE
Bug with highlighting end of lines with wrapped text?

### ISSUE THREAD

**Issue by dspwhite** [jacobslusser/ScintillaNET#33]
My project is a 'Regex helper' program. I may have found a bug when highlighting the end of a paragraph of text in wrapped mode.

Basically, lines are wrapped as expected, but when I highlight the end of the line/paragraph, Scintilla seems to think that the 'fake' newlines that make up the paragraph are also newlines. When in fact, they're just wrapped text. An image is worth a thousand words, so take a look at this:

http://www.skytopia.com/stuff/wildgem-bug.png

I know it's not a bug with my program, since only one match is found as expected (whereas the screenshot looks as though it matches 9!). It doesn't seem like very 'desired' behaviour from Scintilla, so could this be a bug? If not, is there a workaround?

**Comment by jacobslusser** [comment]
I agree this is a bit unusual. I opened a ticket with the native Scintilla team. You can follow the progress here: [https://sourceforge.net/p/scintilla/bugs/1736/](https://sourceforge.net/p/scintilla/bugs/1736/).

**Comment by dspwhite** [comment]
Thanks. It's strange that Notepad++ doesn't have the same problem...

**Comment by jacobslusser** [comment]
I don't know why this didn't occur to me earlier, but your comment about Notepad++ caused me to realize I was answering the question you asked, but not the question you meant to ask. You're assuming Notepad++ doesn't have this problem and I would guess that you came to that conclusion because you've used the Find dialog in Notepad++ to highlight a word or words like your application does and don't see the same behavior. You may not know, however, that when Notepad++ highlights a word it isn't using Styles to do that, it's using Indicators. If the goal of your program is to highlight regex matches it should also be using Indicators to do that.

A brief explanation of Indicators can be found in the wiki article [Find and Highlight Words](https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words) but I threw together a quick sample for you below as well.

```cs
scintilla.Text = "\"The quick brown fox jumps over a lazy dog\" is an English-language pangram—a phrase that contains all of the letters of the alphabet. It is commonly used for touch-typing practice. It is also used to test typewriters and computer keyboards, show fonts, and other applications involving all of the letters in the English alphabet. Owing to its brevity and coherence, it has become widely known.\r\n";
scintilla.WrapMode = WrapMode.Word;

scintilla.Indicators[8].Under = true;
scintilla.Indicators[8].Style = IndicatorStyle.StraightBox;
scintilla.Indicators[8].ForeColor = Color.LightGreen;
scintilla.Indicators[8].OutlineAlpha = 255;
scintilla.Indicators[8].Alpha = 255;

scintilla.IndicatorCurrent = 8;
foreach (var line in scintilla.Lines)
{
    var text = line.Text;
    var pos = line.Position;

    foreach (Match match in Regex.Matches(text, @"known\.\r\n"))
        scintilla.IndicatorFillRange(pos + match.Index, match.Length);
}
```

Using this approach there is no issue with wrapped lines.

**Comment by dspwhite** [comment]
Great. I've converted the program to use indicators instead. I don't think it's faster now, though it fixes the reason behind this thread.

I initially tried indicators, though missed the useful `Under` property which means the highlighting isn't partially obscuring the text it's trying to highlight. Perhaps you could put `scintilla.Indicators[NUM].Under = true;` into the example at: https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words

Thanks again for the help!

**Comment by jacobslusser** [comment]
BTW, the native Scintilla team responded to my bug ticket by essentially saying, "yes this is probably not the desired behavior, but the priority on fixing it is low".

Since you got Indicators working, and I think they're a better solution, and the native Scintilla team doesn't seem in a hurry to fix this, I'm going to close this issue.

**Comment by dspwhite** [comment]
Thanks. Let me know if they ever fix it. One advantage over Indicators is that a small bit at the start of new lines are highlighted, which is nice if you're trying to search for newlines. No hurry though.
