### ISSUE TITLE
View and select sections of a large text file

### ISSUE THREAD

**Issue by TimMakins** [jacobslusser/ScintillaNET#340]
I am in the planning stages of using Scintilla as a 'virtual window' in VB.Net to view a small section of a large text file whilst keeping the rest in memory. I will use a separate vertical scroll control, and load the relevant lines to Scintilla when the scroll-control is clicked or changed.

One aspect I do not understand, though: Imagine a window full of text. You left-click-and-hold, somewhere in the text, then move the mouse to the top of the window. When that happens, the text starts to scroll up, and the text becomes selected, until you release the mouse-button, and the selection completes. My question: How to achieve this? There is no event that I can think of that would respond to a mouse moving up to, and then away from, the top or bottom of a window.

Also, if you have any tips or suggestions on implementing a 'virtual window', I would be interested to hear them.

**Comment by jacobslusser** [comment]
Ya, that's a tricky question. I've wondered about doing the same thing before -- to make Scintilla just a window into a larger file, but I've never tried it.

In a standard Windows Forms control, you could track the mouse movement with a combination of the `MouseMove` event and the `Capture` property on the control. That's basically what you're describing.. capturing the mouse and tracking it even when it leaves the bounds of the control. I'm not sure if either that event or property work on ScintillaNET because the native Scintilla and ScintillaNET do so much overriding of the `WndProc` function that I'm not sure those things still bubble up.
