### ISSUE TITLE
Target framework incompatibility

### ISSUE THREAD

**Issue by byF** [jacobslusser/ScintillaNET#342]
Hi, I've just started to play with writing a UWP app where I wanted to use ScintillaNET. Sadly, it appears not compatible since I'm targeting `uap10.0.15063` while this package supports `net40`.

If I get the compatibility right - I'm new to whole NET/Win ecosystem - then any package which can be used with `uap` needs to support `netstandard`  or `netcore`.

I ran [the portability analysis](https://github.com/jacobslusser/ScintillaNET/files/1156836/ApiPortAnalysis.xlsx) at least.

**Comment by jacobslusser** [comment]
I am by no means an expert on UWP -- furthest from it actually -- however, my limited understanding is that ScintillaNET couldn't possibly be compatible even if it wanted to. ScintillaNET makes use of the Scintilla Win32 component and the Win32 APIs it depends on are not available in UWP apps. So even if it were possible to make ScintillaNET compatible -- which I don't believe it is because it is a Windows Forms control -- I don't think the native Scintilla control could be either.

**Comment by jonasnordlund** [comment]
I came here from Google as I was thinking about a pretty, WinUI style text editor for Windows 11 and using ScintillaNET. While UWP is out, I'd like to remind that the forthcoming WinUI 3.0 combined with relaxed Microsoft Store requirements might work much better, and still offer an accurate look & feel for the latest editions of Windows. In a sense, it's succeeding UWP.
