### ISSUE TITLE
Some way of using/implementing PasswordChar

### ISSUE THREAD

**Issue by tryashtar** [jacobslusser/ScintillaNET#346]
The default .NET `TextBox`es are ugly and frustrating to edit in. Because of this, I typically use `ScintillaNET` for even single-line textboxes. A few simple overrides can disable line breaks if I want it to be single-line, and then I get all the nice Scintilla functionality and customization for all my inputs. Sweet!

However, I have come across my first stumbling block -- making a text box for password input (that just shows •••••••, for example). `TextBox`es get `PasswordChar` to make this easy, and `RichTextBox`es can do it too by setting params.

But I have been unable to implement the same behavior in `ScintillaNET`. I don't see any property that looks similar, and other solutions (like saving the typed text to a hidden variable and putting the asterisks in `Text` when it's changed) did not appear to work either.

I know this isn't the typical usage for what's basically a multiline code editor component, but do you have anywhere to point me? Thank you.

**Comment by jacobslusser** [comment]
There is no built-in functionality for password masking in ScintillaNET (or single-line mode for that matter). I can only suggest that the way I would do it is handle the `InsertCheck` event to capture the input and substitute `•` for any input characters and store the actual text inserted in another variable--or maybe another hidden ScintillaNET control. The `InsertCheck` event should give you enough information to place the caret and insert the edited text in a hidden ScintillaNET control so that might be the easiest thing. I know that's pretty similar to what you already tried, but hopefully that will be the key you're looking for.

**Comment by tryashtar** [comment]
Managed to get it to work. Your idea to use `InsertCheck` instead of `TextChanged` seemed to be the key, as I could simply send the requested characters away, then replace them before they get sent to the control. `TextChanged` wouldn't let me change the text while inside.
This is what I came up with -- it's actually quite concise. Obviously it has the possibly unwanted behavior of `Text` just returning the bullets, but it works for my purposes. Thanks for your help, even for a task that's a bit wonky!
```C#
public class PasswordScintilla : NewScintilla
{
    public string HiddenText { get; private set; } = "";

    public PasswordScintilla()
    {
        this.InsertCheck += PasswordScintilla_InsertCheck;
    }

    private void PasswordScintilla_InsertCheck(object sender, InsertCheckEventArgs e)
    {
        HiddenText = HiddenText.Insert(e.Position, e.Text);
        e.Text = new string('•', e.Text.Length);
    }
}
```
