### ISSUE TITLE
How to use LoadLexerLibrary?

### ISSUE THREAD

**Issue by jeanpf** [jacobslusser/ScintillaNET#349]
Is there a way to use this method in ScintillaNET?

**Comment by Stumpii** [comment]
Never tried it, but here is the method in ScintillaNET (Scintilla.cs):

```
        /// <summary>
        /// Loads a <see cref="Scintilla" /> compatible lexer from an external DLL.
        /// </summary>
        /// <param name="path">The path to the external lexer DLL.</param>
        public unsafe void LoadLexerLibrary(string path)
        {
            if (String.IsNullOrEmpty(path))
                return;

            var bytes = Helpers.GetBytes(path, Encoding.Default, zeroTerminated: true);
            fixed (byte* bp = bytes)
                DirectMessage(NativeMethods.SCI_LOADLEXERLIBRARY, IntPtr.Zero, new IntPtr(bp));
        }
```

**Comment by jeanpf** [comment]
Yes! I found that method but I tried to pass a dll path to it and after tried to set up a Lexer ... it didn't work ..

**Comment by jacobslusser** [comment]
How did you attempt to load the lexer after loading it? I think that process is quite a bit different -- I've never personally done it.

**Comment by jeanpf** [comment]
So, in the other issue #348, I mentioned that I used an external module (is the SciLexer.dll used in Notepad++) to use a Lexer (LexUser) from it. I know that the lexer identifier in the external DLL is 152. So I just call 

`scintilla.Lexer = (Lexer) 152;`

And it works, but not everything (see Issue #348). So, I gave up and started to try to build my own lexer and, in the middle of it, I found out the method LoadExternalLibrary. I tried to set the lexer the same way I did when I was using the external module.

By the way, I have one question about writing one lexer (I know it is kind of off topic): how do you access the keywords you set using SetKeywords method?

**Comment by jacobslusser** [comment]
So many questions...

If the lexer in question is compiled into SciLexer.dll, then you should be able to use `SetModulePath` as you were previously trying to do. My guess, however, is that Notepad++ does not compile their custom lexer into a custom build of SciLexer.dll

Using `LoadLexerLibrary` it is possible to load a DLL which implements a Scintilla lexer *if* that DLL is compiled for that express purpose, e.g. it exports the right lexer functions, etc. Again, I have no idea if Notepad++ uses this approach and if they export their custom lexer in this way.

I would be interested in knowing how Notepad++ does its implementation for future reference if you would like to investigate...

If you choose to implement a custom lexer you will obviously have complete control over which keywords it tokenizes and if you want to make that list customizable. You would not go through the `SetKeywords` API, however, because a custom lexer in ScintillaNET is one that handles the `StyleNeeded` event. The `SetKeywords` method is only used for lexers which implement the native `ILexer` interface like the built-in ones do. So as I said, you can still make your lexer accept a customizable list of keywords, but it would be through a different method.

An explanation of how to create a custom lexer and pass it a list of keywords can be found on the wiki:
[https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting)

**Comment by jeanpf** [comment]
> If the lexer in question is compiled into SciLexer.dll, then you should be able to use SetModulePath as you were previously trying to do. My guess, however, is that Notepad++ does not compile their custom lexer into a custom build of SciLexer.dll

Actually, if you download their source code and compile for yourself you will see that before compiling the main app you have to compile SciLexer.dll. I was able to use the SetModulePath and access the Lexer I wanted but, somehow, the numbers in margin do not work when I use that. What happens is that the MarginsCollection is empty if I use the external module. I really don't know why since I can see that the debugger steps over the whole ScintillaNET constructor.

> The SetKeywords method is only used for lexers which implement the native ILexer interface like the built-in ones do

Oh I see. No problem!
