### ISSUE TITLE
How to add automatic indention.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#35]
When you do a `{` and then press **ENTER**, The caret will go back to the first of the line.  
Ex: *(The | means the caret)*
```
{
|
}
```

Is there is a way to add auto indention.. So it adds a **TAB** on the start of the line.  
Ex: *(The | means the caret)*
```
{
    |
}
```

What I mean here is: Is there an integrated way or I will have to program it myself ?

**Comment by jacobslusser** [comment]
There is not an integrated way to do auto-indenting. That behavior is very language -- and even user -- specific. The native [Scintilla documentation](http://www.scintilla.org/ScintillaUsage.html) includes an example of how you might use the `CharAdded` event to trigger auto-identing. It's written in C++ but fairly easy to follow.

I slapped this together using the `InsertCheck` event and it seems to work pretty well, but I haven't fully tested it:
```cs
private void scintilla_InsertCheck(object sender, InsertCheckEventArgs e)
{
    if ((e.Text.EndsWith("\r") || e.Text.EndsWith("\n")))
    {
        var curLine = scintilla.LineFromPosition(e.Position);
        var curLineText = scintilla.Lines[curLine].Text;

        var indent = Regex.Match(curLineText, @"^\s*");
        e.Text += indent.Value; // Add indent following "\r\n"

        // Current line end with bracket?
        if (Regex.IsMatch(curLineText, @"{\s*$"))
            e.Text += '\t'; // Add tab
    }
}
```

**Comment by JohnyMac** [comment]
Sorry for too late reply.

Here is some bugs with it: 
-------------------------------------------------------------------------------------------------------
![Scintilla Bug](http://i.gyazo.com/9911c0b77d57c2230536041fb4de2f40.gif)
-------------
![Scintilla Bug](http://i.gyazo.com/9986ef17658309a8a3b7946283c49089.gif)
-------------
![Scintilla Bug](http://i.gyazo.com/e8beabec6462b5b41a1f1325ad9aea0c.gif)
---------------------------------------------------------------------------------------------------------

I hope you understand what I mean with just the images :P

**Comment by jacobslusser** [comment]
I certainly didn't mean to imply that the code sample I "slapped" together was perfect. As I said, "I haven't fully tested it" and intended for it to be a starting place for you to arrive at your own solution.

That being said, I think the regular expression I used is too greedy. I used the shorthand character class `\s` because I wanted to match all the leading whitespace, but I forgot that will also match `\r\n` characters. Thus, the search for leading whitespace will also match the `\r\n` characters of lines that contain *only* whitespace and add it to the next line--causing the caret to return all the way to the next line start.

Try switching `@"^\s*"` to `@"^[ \t]*"`. This will make sure only leading space and tab characters are matched, but not `\r\n`. 

Hopefully this will get you past your immediate issue. Just keep in mind that I didn't mean for this to be the perfect solution for automatic indenting. A proper solution will likely also incorporate the current caret position, user preferences, an understanding of the current language, automatic bracket insertion, etc... If/when you come up with something you're happy with, let me know and we can post it along with the other [User Submitted Recipes](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes).

**Comment by JohnyMac** [comment]
Thanks.
The thing is that this was implemented in the old Scintilla, So was just checking.

And about the User submitted recipes, Will do.

**Comment by jacobslusser** [comment]
That's a great point actually... I forgot that there was something like this in the old version of ScintillaNET. Hopefully it should be pretty easy to extract that logic.

**Comment by JohnyMac** [comment]
Ok.. I am back.

I am making it so when the user inputs a `}`, The indention is set subtracted by 4.
But the problem here is that `Scintilla.Lines.Text` is read-only, so how to edit the line independently ?

Thanks in advanced.

**Comment by xonyen** [comment]
Get line start position first, and then use the InsertText method.

**Comment by JohnyMac** [comment]
That's useful for adding text to the line at its beginning.

I want to remove text from the line...

**Comment by JohnyMac** [comment]
@jacobslusser Any answer please ?
I need to be able to edit the whole line and not insert.

**Comment by jacobslusser** [comment]
There are multiple ways to accomplish what you want. For me the approach that first comes to mind is to use the `CharAdded` event. That event is raised after the `}` is entered and places the caret directly after the character added. At that point our objective is to determine if the bracket added is preceded by four spaces or a tab, and if so, remove that text. Since the search API has been on my radar lately I chose to use that to check for the tab or space characters. To use the search API I set the `SearchFlags`, `TargetStart` and `TargetEnd` to search in. Using a `TargetStart` that is greater than the `TargetEnd` will cause it to search in reverse--going backward from the current caret position. When a match is found I remove the appropriate range of text preceding the `{` character.

```cs
private void scintilla_CharAdded(object sender, CharAddedEventArgs e)
{
    if (e.Char == '}')
    {
        var currentPos = scintilla.CurrentPosition;
        scintilla.SearchFlags = SearchFlags.None;

        // Search back from the current position
        scintilla.TargetStart = currentPos;
        scintilla.TargetEnd = 0;

        // Is the bracket following 4 spaces or a tab?
        if (scintilla.SearchInTarget("    }") == (currentPos - 5))
        {
            // Delete the leading 4 spaces
            scintilla.DeleteRange((currentPos - 5), 4);
        }
        else if(scintilla.SearchInTarget("\t}") == (currentPos - 2))
        {
            // Delete the leading tab
            scintilla.DeleteRange((currentPos - 2), 1);
        }
    }
}
```

**Comment by JohnyMac** [comment]
Thanks.

Also, I just discovered that the native scintilla actually contains functions for setting the indention of a line.
I tried and added it to my fork here: https://github.com/JohnyMac/ScintillaNET/commit/89ea34954083a148e08e19c39fadad457b97b453

However, Whenever I try and use my build after recompiling it.. I get this: http://gyazo.com/cf7b1c3adbd030913f22af007c259766

Help appreciated and thanks in advanced.

**Comment by jacobslusser** [comment]
Thanks for the addition of an `Indentation` property. I merged your pull request in commit ff04348d28aa5d3d5f9e615e04e050b4ddb638d7. 

As for why you are having an issue, I'm not sure. It looks to be similar to the error reported in issue #41. For whatever reason, the DllMain of the native Scintilla library will fail (throw an exception). To determine what that is I think we would need to debug the native Scintilla code. Until then I've found that cleaning the solution, deleting anything in your `%LOCALAPPDATA%\Temp\ScintillaNET` folder, and recompiling usually fixes the issue.

**Comment by JohnyMac** [comment]
Okay.

I successfully managed to create the auto-indent.
Here the codes I've used: 

```c#
private void Scintilla_InsertCheck(object sender, InsertCheckEventArgs e)
{
	if ((e.Text.EndsWith("" + Constants.vbCr) || e.Text.EndsWith("" + Constants.vbLf))) {
		int startPos = Scintilla.Lines(Scintilla.LineFromPosition(Scintilla.CurrentPosition)).Position;
		int endPos = e.Position;
		string curLineText = Scintilla.GetTextRange(startPos, (endPos - startPos)); //Text until the caret so that the whitespace is always equal in every line.
		
		Match indent = Regex.Match(curLineText, "^[ \\t]*");
		e.Text = (e.Text + indent.Value);
		if (Regex.IsMatch(curLineText, "{\\s*$")) {
			e.Text = (e.Text + Constants.vbTab);
		}
	}
}

private void Scintilla_CharAdded(object sender, CharAddedEventArgs e)
{
	//The '}' char.
	if (e.Char == 125) {
		int curLine = Scintilla.LineFromPosition(Scintilla.CurrentPosition);
		
		if (Scintilla.Lines(curLine).Text.Trim() == "}") { //Check whether the bracket is the only thing on the line.. For cases like "if() { }".
			SetIndent(Scintilla, curLine, GetIndent(Scintilla, curLine) - 4);
		}
	}
}

//Codes for the handling the Indention of the lines.
//They are manually added here until they get officially added to the Scintilla control.
#region "CodeIndent Handlers"
	const int SCI_SETLINEINDENTATION = 2126;
	const int SCI_GETLINEINDENTATION = 2127;
	private void SetIndent(ScintillaNET.Scintilla scin, int line, int indent)
	{
		scin.DirectMessage(SCI_SETLINEINDENTATION, new IntPtr(line), new IntPtr(indent));
	}
	private int GetIndent(ScintillaNET.Scintilla scin, int line)
	{
		return (scin.DirectMessage(SCI_GETLINEINDENTATION, new IntPtr(line), null).ToInt32);
	}
#endregion
```

You may add it to the recipes thing if you want to.
And thanks for your time.

**Comment by JohnyMac** [comment]
Also, Please create a new release ASAP.

**Comment by KaosKidd** [comment]
Hi all;
  Well, I was following this all the way through until I saw that it was C#.  I really need to change my language of choice, eh?  Anyway, here is a very simple Auto indent for vb.net Visual Basic writers :)

     Private Sub Editor_CharAdded(sender As Object, e As ScintillaNET.CharAddedEventArgs) Handles Editor.CharAdded
        Dim CurrentLine As ScintillaNET.Line = Editor.Lines.Item(Editor.CurrentLine)
        Dim CurrentPosition = Editor.CurrentPosition
        If CurrentLine.Text = vbCrLf Then
            CurrentLine.Indentation = Editor.Lines.Item(Editor.CurrentLine - 1).Indentation
            Editor.CurrentPosition = CurrentPosition + CurrentLine.Indentation
            Editor.SelectionStart = Editor.CurrentPosition
        End If
    End Sub

Thanks again for such an awesome control!
Fred

**Comment by JohnyMac** [comment]
I use VB.NET myself in my project btw.. But I just translated to C# to get fast help.

**Comment by ajayre** [comment]
Did anyone make a copy of that gist from Ahmad45123 before it was deleted? Would be silly to reinvent the wheel. Thanks.

**Comment by Ahmad45123** [comment]
@ajayre I didn't delete it. I changed my username.
Here's the gist: https://gist.github.com/Ahmad45123/f2910192987a73a52ab4
