### ISSUE TITLE
Scintilla.Text is not updated when Scintilla.ReadOnly is set to true

### ISSUE THREAD

**Issue by kasthack** [jacobslusser/ScintillaNET#360]
Version: 3.6.3 (nuget)

Reproduction:

* create scintilla control (`sct`) / add to form / usual stuff
```csharp
sct.ReadOnly = true;
sct.Text = "test";
```
Current behavior:

* `sct.Text` stays unchanged

Expected behavior:

* `sct.Text` becomes "test"

Broken cases:

* Apps where Scintilla is only used to show highlighted source code w/line numbers without allowing user to edit it.

Possible workarounds:

* Manually setting `Scintilla.ReadOnly` to `false` and back to `true` but this becomes quite complicated when complex data bindings are used.
* Overriding `Text` property in an inherited class

**Comment by jacobslusser** [comment]
So ya... this is standard Scintilla behavior. I've always questioned it myself, because the standard .NET text controls use the `ReadOnly` property to mean "user-readonly", but programatic access is still possible. Scintilla, however, uses `ReadOnly` to mean "user-and-programmatic-readonly".

Your suggested approach of toggling the flag when you set the `Text` property is probably the best workaround, however, I think this belongs in your application and not in the ScintillaNET base code.

**Comment by xamidi** [comment]
This "standard Scintilla behavior" leads to unnecessary instructions when using "user-readonly" text boxes, that might even be user-exploitable (due to removals of "user-readonly" on programmatic modifications). Either there should be an option to define whether it is "user-only" or "user-and-programmatic", or turned to "user-only". In general it is bad practice to quietly not do what the developer told an algorithm to do, such as modifying their own variables. Also, the kind of limitations that should affect users should not affect developers (who are very much like the admins of their code and should not be restricted except by their own policies).
