### ISSUE TITLE
Number of lines when using text wrap around

### ISSUE THREAD

**Issue by TalibKweli** [jacobslusser/ScintillaNET#363]
At the moment when I check the number of lines, a line that has been wrapped around and displays as 3 lines, is still counted as 1 line. Is there a way to determine the number of lines displayed when using text wrap around? Thanks

**Comment by skyhoshi** [comment]
I'm not sure if it's possible but could you could the "Columns" (Characters) viewable in a given row? to know where the screen Wraps the text? 

That is assess the size of the window and the size of the text, then extrapolate the number of "Columns" (Characters) that will give you the "Visible Row Count"

So as apart of your "Row Check" your taking the Number of Columns (characters) visible, then comparing that to the number of columns (characters) the text takes up then providing that to "Designate" the Visible Row. 

the problem is when you resize the window. you will experience a change in the result. 

You should also take into account the "Visible Row Count" and Actual Row Count where when Word Wrap is ON, the Visible Row Count will always be => the Actual Row Count.

Hope this helps.

**Comment by jacobslusser** [comment]
Generally speaking, most of the ScintillaNET API works on "document" line counts and you'll see the documentation refer to it this way. What you want is "display" line count. Try the `Line.WrapCount` property.

**Comment by TalibKweli** [comment]
Thanks jacobslusser, Line.WrapCount is what I need
