### ISSUE TITLE
Determine if a line is a FoldPoint, and FoldState

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#40]
Will this be a feature that will be added in the future?

**Comment by jacobslusser** [comment]
I committed 21754eae31afe1fe90deac0ae9a1b91d8e56936f which should have what you need. There is a lot in the commit to sift through, but the properties you're probably looking for are `Line.FoldLevel` and `Line.FoldLevelFlags`. The first controls the nesting level of the line and the second whether the line is a fold point.

**Comment by theryan722** [comment]
What value for FoldLevel determines if it is folded, or unfolded? Is it unfolded if it is 1024?

**Comment by jacobslusser** [comment]
The `FoldLevel` sets the nesting of the line and any subsequent lines so that they are considered grouped (or children). The first line in that sequence must have the `FoldLevelFlags.Header` flag set. It doesn't get set for you; you must set it. My guess is that you have not set that flag on the fold point line.

P.S. This is all only necessary if you are creating your own folding / lexer logic. If you are looking to get folding working for one of the included lexers, see the [Automatic Code Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding) wiki article.
