### ISSUE TITLE
SciLexer.dll

### ISSUE THREAD

**Issue by cRUSHER-HLG** [jacobslusser/ScintillaNET#416]
Hello Guys, 
I want to ask for what the SciLexer.dll is needed? 

I understand that the ScintillaNet is just a wrapper from SciLexer but why we dont integrate the scilexer stuff in the same lib that is not a win32 unmanaged library for c#?

As you have write it, that the scilexer.dlls need to be puted into the temp folder maybe destroys the load mechanism on Linux Systems? So why not change the path combile in the method GetModulePath located in Scintilla.cs Line 957 to the same folder as the application. I changed it for me that the scilexer are located in the same folder as the application in /Libs folder with /x86 and /x64 and then choosing the one. So you dont need to write in temp folder where the most people dont will find it.

**Comment by jacobslusser** [comment]
If you would like to place the SciLexer.dll in your application folder and call `SetModulePath` then you are welcome to do that. That is what it is for. See: 

[https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll).

The user's temp folder is used because it is globally accessible even when in Visual Studio - a requirement if you want to use ScintillaNET at design time.
