### ISSUE TITLE
Phpscript lexer ignores keywords? Am i missing something?

### ISSUE THREAD

**Issue by gtsiros** [jacobslusser/ScintillaNET#425]
I do not know what else i could add here to help you, i am sorry.
![image](https://user-images.githubusercontent.com/3066444/50124282-97eb1400-026c-11e9-95fa-f02983f2d6b2.png)

```vb
Public Class TScintillaBarebones
    Inherits System.Windows.Forms.Form
    <System.STAThread()> Shared Sub Main(args() As String)
        System.Windows.Forms.Application.EnableVisualStyles()
        System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(False)
        System.Windows.Forms.Application.Run(New TScintillaBarebones)
    End Sub
    WithEvents _ed As ScintillaNET.Scintilla
    Sub New()
        Me._ed = New ScintillaNET.Scintilla
        Me._ed.Dock = System.Windows.Forms.DockStyle.Fill
        Me._ed.SetKeywords(0, "keyword fooword barword bazword")
        Me._ed.Lexer = ScintillaNET.Lexer.PhpScript
        Me._ed.SetKeywords(0, "keyword fooword barword bazword")
        Me._ed.Text = "keyword fooword KEYWORD FOOWORD $var notkeyword"
        Me._ed.StyleResetDefault()
        Me._ed.Styles(ScintillaNET.Style.Default).BackColor = System.Drawing.Color.Black
        Me._ed.Styles(ScintillaNET.Style.Default).ForeColor = System.Drawing.Color.White
        Me._ed.StyleClearAll()
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Default).BackColor = System.Drawing.Color.Black
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Default).ForeColor = System.Drawing.Color.Blue
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Variable).BackColor = System.Drawing.Color.Black
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Variable).ForeColor = System.Drawing.Color.Cyan
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Word).BackColor = System.Drawing.Color.Red
        Me._ed.Styles(ScintillaNET.Style.PhpScript.Word).ForeColor = System.Drawing.Color.Green
        Me._ed.SetKeywords(0, "keyword fooword barword bazword")
        Me._ed.Lexer = ScintillaNET.Lexer.PhpScript
        Me._ed.SetKeywords(0, "keyword fooword barword bazword")
        Me.Controls.Add(Me._ed)
    End Sub
End Class
```

**Comment by gtsiros** [comment]
doesn't look like it.
![image](https://user-images.githubusercontent.com/3066444/55671492-49a06600-5899-11e9-8ed0-a1d90d5c9254.png)

did you try the code?

edit: or, can you show me your code?

**Comment by xv** [comment]
You're right, something is wrong. Keywords are not highlighting, but other PHP styles are working fine. I'm extremely busy the next 4 days. I'll dig into it later and see what I can find.

**Comment by xv** [comment]
You're right, wrapping `<?php ... ?>` has nothing to do with this. What I did find is that PHP uses index 4 for keywords. So, `scintilla.SetKeywords(4, "echo if else int bool");` should work. This is probably because The PHP lexer is not standalone. It's actually part of the HTML lexer.

See: https://github.com/mirror/scintilla/blob/master/lexers/LexHTML.cxx#L2449

**Comment by xv** [comment]
You're right, wrapping <?php ... ?> has nothing to do with this. What I did find is that PHP uses index 4 for keywords. So, scintilla.SetKeywords(4, "echo if else int bool"); should work. This is because the PHP lexer is not standalone. It's actually part of the HTML lexer.

See: https://github.com/mirror/scintilla/blob/master/lexers/LexHTML.cxx#L2449

**Comment by xv** [comment]
You're right, wrapping with `<?php ... ?>` has nothing to do with this. What I did find is that PHP uses index 4 for keywords. So, `scintilla.SetKeywords(4, "echo if else int bool");` should work. This is because the PHP lexer is not standalone. It's actually part of the HTML lexer.

See: https://github.com/mirror/scintilla/blob/master/lexers/LexHTML.cxx#L2449

**Comment by gtsiros** [comment]
just as i was about to send this 

![image](https://user-images.githubusercontent.com/3066444/55681352-34c1e200-592e-11e9-98bd-83c0ba71e44f.png)
