### ISSUE TITLE
Find/Replace methods?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#43]
Are these planned to be implemented? I know the Find/Replace dialog is not planned to be implemented as the project is aimed to be kept cross-platform, but what about just the methods so the user could implement their own? Possibly such as Find, Replace, FindAll, etc. and Regex searching?

**Comment by jacobslusser** [comment]
The Find API should be mostly there. To get a primer on it you might check out the [Find and Highlight Words](https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words) wiki article. Those methods also support the Scintilla flavor of regular expressions.

I believe I have more work to do though getting the replace API completed. Let me know what you find (no pun intended).

Also, I don't believe I plan to support the .NET regex flavor in ScintillaNET incase you were asking about that. The reason is because it is a VERY expensive operation to perform. .NET regular expressions can only be performed on `string` types and that means running a .NET regex on the ScintillaNET text would me dumping the whole document to a string. I've seen problems in the past when users don't understand that that is the cost and so I don't want to put in an API where users can hang themselves. My opinion is that if users want to use .NET regular expressions they can do so by getting the document text and running it themselves--and manage their own performance expectations accordingly. Otherwise, they should use Scintilla regular expressions.

**Comment by theryan722** [comment]
Sounds good, how do you specify a regex that is Scintilla as opposed to .NET's?

**Comment by jacobslusser** [comment]
This is obviously one of those things that I need to do a better job of documenting... (mental note, document Scintilla regular expressions). From the Scintilla documentation:

```
```

**Comment by jacobslusser** [comment]
Commit 13148f1396a3c0907f6b907d66f2b74676220e54 completes the Search/Replace API by adding `ReplaceTarget`. More documentation to follow....

**Comment by theryan722** [comment]
What is the reasoning for this weird syntax? Regex is complicated as it is for me, oh well you learn something new everyday.

**Comment by theryan722** [comment]
Also, when do you think documentation will be up for GetTag, ReplaceTarget, etc? There is no rush of course, I'm just wondering.

**Comment by jacobslusser** [comment]
> What is the reasoning for this weird syntax? Regex is complicated as it is for me, oh well you learn something new everyday.

I don't know the history of why Scintilla uses the control characters it does for regular expressions. Technically, there is no formal definition of regular expressions syntax, there is only common conventions and Scintilla doesn't always follow those. The major deviations are these:

1. Scintilla uses `\<` and `\>` for word boundaries instead of `\b`.
2. Scintilla uses `\(` and `\)` for capture groups instead of `(` and `)`.
3. Scintilla uses `\n` for replacement instead of `$n`.

As I mentioned, you can fix number 2 pretty easily by using the `SearchFlags.Posix`, but there is no alternative to `\<`, `\>`, and `\n`. You'll just have to get used to those when dealing with Scintilla. The other control characters are pretty much standard for all regular expression engines.

BTW, many years ago I decided to learn regular expressions and went through all the tutorials at [http://www.regular-expressions.info/](http://www.regular-expressions.info/) and purchased the RegexBuddy software. It was one of the best things I ever did.

> Also, when do you think documentation will be up for GetTag, ReplaceTarget, etc? There is no rush of course, I'm just wondering.

They are fully documented now. Get latest and check them out. I only meant to say that I'm working on a recipe/tutorial to further explain their use.

**Comment by JohnyMac** [comment]
If you are creating an IDE, An idea is to just use `String.Replace` and replace all the changes on the regex statement that is received from the user.

Like: `regexString = regexString.Replace("\(", "(")`..
