### ISSUE TITLE
Demo Application - Update Frequency

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#45]
I began working on a demo application in both C# and VB. An issue that I ran into was the fact that this project is updated fairly often (good), but that would mean the demo application would be obsolete quite often. What are your thoughts on the update frequency for the demo application?

**Comment by jacobslusser** [comment]
Is your hope to have 100% API coverage in the demo app? I'm not sure that's possible. The rate at which APIs are added to ScintillaNET will always be faster than you could keep up with in a demonstration application. If anything, I would suggest that you just try to show the core principles of using the control and answers to common questions.

BTW, thanks for giving it a go and good luck.

**Comment by theryan722** [comment]
Sounds good to me. Are there are any features or aspect of the API you would like me to place in the demo?

**Comment by jacobslusser** [comment]
I don't have any personal requests, but then again I'm probably not the best person to ask because I'm already pretty well acquainted with ScintillaNET.

I would suggest going through the issues list and gleaning what you can from those, adding most/all of the recipes currently documented in the Wiki, and then just get what you have out there. My experience is that users will provide you with additional feedback and direction.
