### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by sirgru** [jacobslusser/ScintillaNET#471]
Hi, I noticed in Scintilla-based editors, such as Notepad++, there is no smooth scrolling. Scrolling is by line, and issue tracker for Scintilla shows "Won't fix" status on the issue posted a long time ago.

I have tried the https://github.com/robinrodricks/ScintillaNET.Demo and there was also scrolling by line. Can you conform it is not possible to scroll by pixel in Windows Forms and WPF?

**Comment by xv** [comment]
Scintilla doesn’t have any implementation for smooth scrolling so it’s not currently possible.

I doubt the author of Scintilla is willing implement the feature himself. If someone is really determined to have this feature, they’ll have to contribute the code themselves.

There’s an open request ticket since 2010:
https://sourceforge.net/p/scintilla/feature-requests/688/

In WPF, things like smooth scrolling are probably much easier to implement since it doesn’t use GDI/+ for drawing.

**Comment by KnIfER** [comment]
> In WPF, things  are probably much easier to implement ....

Even for pure win32 api, it's easy to achieve simple smooth scrolling based on timer:

https://user-images.githubusercontent.com/11593903/133339169-2788a9a5-18a6-4c84-be15-9c50f216033b.mp4

**Comment by ericoporto** [comment]
@KnIfER can you point to the source code of the smooth scrolling?

Edit: found but it require modifying the scintilla native source code:
https://github.com/KnIfER/Scintilla/commit/6cb2f94d84a3f2220f1301dd630975e40b2ff321
