### ISSUE TITLE
Set text for specific line

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#57]
I'm probably skipping over it, but how do you set the text of a specific line? The **Scintilla.Lines(#).Text** only gets the text.

**Comment by jacobslusser** [comment]
Precisely. There is no API to set the text for a line. It's easy to forget that Scintilla manages a document, not a collection of lines. This is something that I mention in the project [README.md](https://github.com/jacobslusser/ScintillaNET) under the "Keeping it Consistent" section.

From a technical standpoint, it's because setting the text to `"Hello\r\nWorld"` would actually result in two lines of text, not one; or just as easily, you could set the text to `""` leaving no line at all. Your `Line` object would then be in an undefined state.

If you want to do the equivalent of replacing the line text you'll need to use the `Line[0].Position` and `Line[0].EndPosition` to get the text range and then replace that range of text in the document. It's the document that manages the text, not the `Lines` collection.

**Comment by theryan722** [comment]
Thank you, because 2.6 had Lines.Tex as a property so portions of my code
used it. I will create a custom method for myself. Thanks!

On Fri, Jul 3, 2015 at 12:11 AM, jacobslusser <notifications@github.com>
wrote:

> Precisely. There is no API to set the text for a line. It's easy to forget
> that Scintilla manages a document, not a collection of lines. This is
> something that I mention in the project README.md
> <https://github.com/jacobslusser/ScintillaNET> under the "Keeping it
> Consistent" section.
>
> From a technical standpoint, it's because setting the text to
> "Hello\r\nWorld" would actually result in two lines of text, not one; or
> just as easily, you could set the text to "" leaving no line at all. Your
> Line object would then be in an undefined state.
>
> If you want to do the equivalent of replacing the line text you'll need to
> use the Line[0].Position and Line[0].EndPosition to get the text range
> and then replace that range of text in the document. It's the document that
> manages the text, not the Lines collection.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobslusser/ScintillaNET/issues/57#issuecomment-118226569>
> .
>



-- 
Ryan O'Day
------------------------------------
Business Email: bionetworkscorp@gmail.com
Business Website: www.bionetworkscorp.net
