### ISSUE TITLE
Just wanted to say thank you.

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#58]
You have cost me over a week of porting, error fixing, and getting my hands dirty, all just to transition from the old scintilla to this one. And it was the best decision I could have made. For once I was forced to view the source code and as a result, as well as through you teaching and helping me, I learned  more about Scintilla and various other topics in this week alone then I did from the months of using the old Scintilla.

Thank you, I've already said it, but I will be sticking around to help/contribute in any way I can.

**Comment by JohnyMac** [comment]
Your title is bad lol..
I thought for a moment that you messed up your codes because of him...lol

And actually yes, I am creating an IDE and till new I am very happy with Scintilla and not looking forward to change it at all..

It just misses one thing and it will be the greatest editor, maybe better then those paid ones.
It misses a good autocomplete, with support of images near text and the ability to change its colors.

**Comment by theryan722** [comment]
Yeah, that would be pretty awesome. Also, I'm pretty sure that the AutoComplete list does support images, but I doubt this wrapper exposes that support, and I don't think it was pretty to do either.

Plus I have seen Scintilla editors that have images in their autocomplete lists.

**Comment by jacobslusser** [comment]
LOL... thanks for the compliments. I'm glad you're both enjoying the project.
