### ISSUE TITLE
Why is BackColor not supported?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#63]
In the sourcecode for ScintillaNET it says BackColor is not supported.

**Comment by JohnyMac** [comment]
Its probably because he wasn't free to implement it ? :/

However, by reading Scintilla's documentation.
You can use **SCI_SETWHITESPACEBACK** to set the whitespace color.
And use **SCI_SETSELBACK** to set the selected text back-color.

I don't have any clue though.. I just got all the revelant functions from the Scintilla Doc: http://www.scintilla.org/ScintillaDoc.html

**Comment by theryan722** [comment]
The property is there in Scintilla.cs, but it is disabled saying it is not supported.

**Comment by jacobslusser** [comment]
In the new version of ScintillaNET I intentionally avoided supporting a `BackColor` property because the meaning is ambiguous. What should the property be? The BackColor of whitespace as suggested by @JohnyMac? The BackColor of the `Style.Default`? or selected text? or something else? In the last version of ScintillaNET we couldn't agree and so `BackColor` became a sledgehammer and set the background color of every style. 

This go around I decided that Scintilla doesn't support a universal background color and so I didn't think ScintillaNET should either. 

P.S. I used the same approach for the `ForeColor` and `Font` properties.

**Comment by theryan722** [comment]
So there is no way to set the background color of the control? Darn

**Comment by jacobslusser** [comment]
`Scintilla.Styles[Style.Default].BackColor` is probably what you're looking for.

**Comment by theryan722** [comment]
The code does not seem to affect the control.
