### ISSUE TITLE
[Question] For some reason regex that are used in the .Text property doesn't work.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#64]
Okay.. IDK what happens exactly.
But this regex code here: https://github.com/JohnyMac/ExtremeParser/blob/master/ExtremeParser/Parser.vb#L29-L37 doesn't match at all with the text that I get from the .Text property in Scintilla.

If I replaced Scintilla with a RichTextBox and try it, it works great.

And the problem is that the remaining regex in the file works.. Its only that regex which is affected :/

**Comment by jacobslusser** [comment]
There is nothing special about the `Scintilla.Text` property... it's a `String` just like any other.

Something else is likely the issue. If you want to share some sample text you're passing in the `code` variable I might be able to tell you more.

**Comment by JohnyMac** [comment]
```c#
/**
**	<summary>GetPlayerName</summary>
**	<param name="playerid">The ID of the player.</param>
**	<returns>
**		The name if the player.
**	</returns>
**	<remarks>
**		Gets the name of the player that is showen above him.
**	</remarks>
*/
public GetPlayerName(playerid)
{
	new name[MAX_PLAYER_NAME]; GetPlayerName(playerid, name, sizeof(name); return name;
}
```

Here the thing that is similer to phpdoc should be detected by regex.

**Comment by JohnyMac** [comment]
Actually, Here is what happens exactly.. Bellow is a form with a RichTextBox and Scintilla and both has the same codes except that the above button gets the `Scintilla.Text` and the other gets the `RichTextBox.Text`..

The RichTextBox: 
![RichTextBox](http://i.gyazo.com/6be98bcc299aea4f6959eddb6da8e521.gif)

Scintilla: 
![Scintilla](http://i.gyazo.com/6875c4c5206fb84a35f1cc3a12c76c94.gif)

However, After debugging that exception.. Its because the Regex doesn't match anything.

**Comment by JohnyMac** [comment]
Ahhhhhhh... I found it after honestly 5 hours of thinking on it.
As honestly its pretty pretty weird.

Its because scintilla uses `\n\r` for line endings while richtextbox was using only `\r` for line endings.
Its mainly just a problem with my regex however I am not really very great at regex.. How can I make it to detect newlines in general, /n and /r.

Thanks in advanced.

**Comment by jacobslusser** [comment]
Glad you found it. BTW, Scintilla has an `EolMode` property. Set it to `EolMode.Lf` to have Scintilla use only `"\n"` when the user hits the `Enter` key instead of `"\r\n"`.

That will make sure Scintilla uses the line ending mode you want for when users are typing, but there is also the scenario of when a user pastes code. If you want to ensure that pasted code matches your `EolMode` property you should also set the `PasteConvertEndings` property to `true` and Scintilla will automatically normalize all the line endings in the pasted text.

Finally, you have the scenario of what to do when text is loaded from a file (i.e. text wasn't entered by the user and text wasn't pasted). Not to worry. The `ConvertEols` method is yet another way to normalize all the line endings.

BTW, I'm assuming you meant RichTextBox was using only `"\n"` instead of `"\r\n"` because it is VERY uncommon to see only `"\r"` in Windows. Typically in Windows you'll see `"\r\n"` --  or rarely, `"\n"`, but hardly ever will you see `"\r"`.

**Comment by JohnyMac** [comment]
Its /n yes.. sorry about that :P

Also, Just a quick question.. What will be more efficient ?
Using the properties to convert the line endings or to just use `.Replace` when I need it to be Lf.

And thanks :)

**Comment by jacobslusser** [comment]
Performance testing is the only way to be sure, but I believe using Scintilla to do this would be fastest. Assuming you use `ConvertEols`  and then get the `Text`, you're doing one traversal of the document looking for line breaks and one copy from Scintilla to string. If you used `Text.Replace` you would be doing one copy from Scintilla to string, one traversal, and then another string copy because .NET strings are immutable.

P.S. That's also assuming this is being done every time--which I believe you can avoid. My hope is that if you set the `EolMode` and `PasteConvertEndings` properties correctly, you won't need to ever use `ConvertEols` or `Text.Replace` because the line endings will never be incorrect.

P.P.S. That's also assuming you want to go this route at all instead of just changing your regular expression to support both `"\n"` and `"\r\n"`.

**Comment by JohnyMac** [comment]
```
P.P.S. That's also assuming you want to go this route at all instead of just changing your regular expression to support both "\n" and "\r\n".
```

If you can see above, `How can I make it to detect newlines in general, /n and /r.`

That was already my main question.. How can I do that ?
Here is my regex: `(?:\/\*\/{1,}\*\/[\s\S])((?:\/\/\/.*[\s\S])+)(?:\/\*\\{1,}\*\/)`
I use [\s\S] for new-lines, I am pretty sure thats the issue :P.. What can be a replacement for it ?

**Comment by JohnyMac** [comment]
Ok, Fixed by replacing `[\s\S]` with `(?:\r\n|\r|\n)` to accept all types of line ending,
