### ISSUE TITLE
problem in pascal folder marker

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#67]
after using begin ....  end
and hit enter many times the folder marker dont stop
there is a solution for this problem
also can i use Style.Pascal.Word2 in pascal lexer or no

i use the code in issue #65

![screenshot 16h 28m 17s](https://cloud.githubusercontent.com/assets/13167974/8526063/21e3dc76-23fc-11e5-9e5f-15fd893e0f11.jpg)

**Comment by METOUIA7** [comment]
i use the code in  issue https://github.com/jacobslusser/ScintillaNET/issues/65

**Comment by jacobslusser** [comment]
No, you cannot use `Style.Pascal.Word2` constants because even if it existed it wouldn't do anything. The `Style.Pascal.Word` style matches keyword list 0 and the Pascal lexer doesn't support any more keyword lists than that.

As for your screenshot:

Theory 1: it almost looks like your marker symbols may be a bit off. If the `begin` keyword should be the start of a block and the `end` keyword the end, then I think the fold marker should be showing a minus (expanded block) rather than a plus (collapsed block). If that is true it could imply that your other symbols are off as well and you are showing vertical line makers in incorrect places. i.e. it's a display problem, not a data problem.

Theory 2: The Pascal lexer doesn't work the way you think it does. This is code built into the native Scintilla component so I'm no expert on it. You could probably learn a lot though about its capabilities and options by reading the source code: [http://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexPascal.cxx](http://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexPascal.cxx).

**Comment by METOUIA7** [comment]
This is the code that i used in my project

Scintilla1.SetProperty("tab.timmy.whinge.level", "1");
Scintilla1.SetProperty("fold", "1");


Scintilla1.Margins(2).Type = MarginType.Symbol;
Scintilla1.Margins(2).Mask = Marker.MaskFolders;
Scintilla1.Margins(2).Sensitive = true;
Scintilla1.Margins(2).Width = 20;

for (int i = Marker.FolderEnd; i <= Marker.FolderOpen; i++) {
	Scintilla1.Markers(i).SetForeColor(SystemColors.ControlLightLight);
	Scintilla1.Markers(i).SetBackColor(Color.Black);
}

Scintilla1.Markers(Marker.Folder).Symbol = MarkerSymbol.BoxPlus;
Scintilla1.Markers(Marker.Folder).SetBackColor(SystemColors.ControlText);
Scintilla1.Markers(Marker.FolderOpen).Symbol = MarkerSymbol.BoxMinus;
Scintilla1.Markers(Marker.FolderEnd).Symbol = MarkerSymbol.BoxPlusConnected;
Scintilla1.Markers(Marker.FolderEnd).SetBackColor(SystemColors.ControlText);
Scintilla1.Markers(Marker.FolderMidTail).Symbol = MarkerSymbol.TCorner;
Scintilla1.Markers(Marker.FolderOpenMid).Symbol = MarkerSymbol.BoxMinusConnected;
Scintilla1.Markers(Marker.FolderSub).Symbol = MarkerSymbol.VLine;
Scintilla1.Markers(Marker.FolderTail).Symbol = MarkerSymbol.LCorner;

Scintilla1.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);

**Comment by jacobslusser** [comment]
After some trial and error and digging through Notepad++ code, I think you should change your lexer properties to:

```cs
scintilla.SetProperty("fold", "1");
scintilla.SetProperty("fold.compact", "0");
```

**Comment by METOUIA7** [comment]
THANKS ALOT FOR HELP IT S WORK WELL

![screenshot 00h 05m 53s](https://cloud.githubusercontent.com/assets/13167974/8559526/c15f256c-2505-11e5-947c-a99e6ef5d9b0.jpg)
