### ISSUE TITLE
Copy argument CopyFormat.Html doesn't work

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#88]
The CopyFormat.RTF works just fine, however when you attempt to copy as Html nothing happens.

**Comment by jacobslusser** [comment]
Works for me. Can you be more specific? Have you tried using a clipboard viewer application to determine if the HTML is actually getting to the clipboard or not? Are you able to capture any exceptions? First chance exceptions?

**Comment by theryan722** [comment]
Okay so it is being copied as HTML format, but I am not able to paste it anywhere. Do you have to specifically handle HTML in the clipboard?

**Comment by jacobslusser** [comment]
It's entirely up to the application you are pasting to which clipboard format(s) it supports and wants to use. Scintilla can put the data on the clipboard, but it can't force an application to use it. 

If you think that copying both RTF and HTML to the clipboard is causing the application to prefer RTF, then you could try copying just HTML to the clipboard.

P.S. just a reminder that Scintilla is copying HTML to the clipboard in "HTML clipboard" format--so that other applications which support it can render the HTML. That's not the same as an HTML string being placed on the clipboard.

**Comment by theryan722** [comment]
Is is possible to export it as a string instead of HTML?

**Comment by jacobslusser** [comment]
Yes. See issue #78. It's on my to-do list.

**Comment by theryan722** [comment]
Oh wow, thanks.
